// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ltrstchain/bridge/bridge.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Source identifies which bridge brought an asset onto the chain. This
// is informational / UI-facing. The trust assumptions are enforced by
// governance when registering the entry.
type BridgeSource int32

const (
	BridgeSource_BRIDGE_SOURCE_UNSPECIFIED BridgeSource = 0
	// Noble issues native Circle USDC over IBC. Highest trust in the
	// Cosmos ecosystem for USDC.
	BridgeSource_BRIDGE_SOURCE_NOBLE BridgeSource = 1
	// Axelar is a Cosmos chain whose General Message Passing wraps EVM
	// (and other) assets into an IBC-transferable form.
	BridgeSource_BRIDGE_SOURCE_AXELAR BridgeSource = 2
	// Wormhole Gateway is a Cosmos chain that bridges non-Cosmos chains
	// (Solana, Ethereum pre-native, Sui, etc.) into IBC form.
	BridgeSource_BRIDGE_SOURCE_WORMHOLE BridgeSource = 3
	// Any other IBC counterparty not specifically one of the above.
	BridgeSource_BRIDGE_SOURCE_IBC_OTHER BridgeSource = 4
)

var BridgeSource_name = map[int32]string{
	0: "BRIDGE_SOURCE_UNSPECIFIED",
	1: "BRIDGE_SOURCE_NOBLE",
	2: "BRIDGE_SOURCE_AXELAR",
	3: "BRIDGE_SOURCE_WORMHOLE",
	4: "BRIDGE_SOURCE_IBC_OTHER",
}

var BridgeSource_value = map[string]int32{
	"BRIDGE_SOURCE_UNSPECIFIED": 0,
	"BRIDGE_SOURCE_NOBLE":       1,
	"BRIDGE_SOURCE_AXELAR":      2,
	"BRIDGE_SOURCE_WORMHOLE":    3,
	"BRIDGE_SOURCE_IBC_OTHER":   4,
}

func (x BridgeSource) String() string {
	return proto.EnumName(BridgeSource_name, int32(x))
}

func (BridgeSource) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2b2dec4cec3511ef, []int{0}
}

// BridgeAsset is the on-chain registry record for an IBC-bridged
// asset. It ties the opaque ibc/<hash> denom users see in x/bank to
// human-meaningful display metadata and an origin attestation.
type BridgeAsset struct {
	// ibc_denom is the canonical bank denomination, e.g.
	// "ibc/498A0751C7A53C569BE0F84EE4E6FA3B9D6C3B2FBEDFBF37EA0F67F8E56BDBC".
	// It is the hash-derived denom that x/ibc-transfer writes into
	// x/bank on receipt.
	IbcDenom string `protobuf:"bytes,1,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	// display_symbol is the short ticker used in UIs (e.g. "USDC").
	DisplaySymbol string `protobuf:"bytes,2,opt,name=display_symbol,json=displaySymbol,proto3" json:"display_symbol,omitempty"`
	// display_name is the long name used in UIs (e.g. "USD Coin (Noble)").
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// decimals is the number of decimal places the source chain uses.
	// Most stablecoins use 6; ETH uses 18.
	Decimals uint32 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// source identifies the bridge category (see BridgeSource).
	Source BridgeSource `protobuf:"varint,5,opt,name=source,proto3,enum=ltrstchain.bridge.BridgeSource" json:"source,omitempty"`
	// source_chain_id is the IBC counterparty chain id that originated
	// this asset (e.g. "noble-1", "axelar-dojo-1", "gateway-1").
	SourceChainId string `protobuf:"bytes,6,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"`
	// source_denom is the denom on the source chain, before any wrapping
	// (e.g. "uusdc" on Noble, "uusdc" on Axelar after conversion from
	// ERC-20, "solana-usdc" on Wormhole Gateway).
	SourceDenom string `protobuf:"bytes,7,opt,name=source_denom,json=sourceDenom,proto3" json:"source_denom,omitempty"`
	// channel_id is the ICS-04 channel id on THIS chain that the asset
	// arrives through (e.g. "channel-0"). Packets via any other channel
	// that hash to the same ibc_denom are still honoured by x/bank, but
	// the registry canonicalises one blessed path.
	ChannelId string `protobuf:"bytes,8,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// verified flags assets that have passed governance-level scrutiny.
	// UIs are encouraged to hide unverified assets by default.
	Verified bool `protobuf:"varint,9,opt,name=verified,proto3" json:"verified,omitempty"`
	// registered_height records the chain height at which this record
	// was first written. Useful for auditing registry drift.
	RegisteredHeight int64 `protobuf:"varint,10,opt,name=registered_height,json=registeredHeight,proto3" json:"registered_height,omitempty"`
	// updated_height records the height of the last mutation.
	UpdatedHeight int64 `protobuf:"varint,11,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
}

func (m *BridgeAsset) Reset()         { *m = BridgeAsset{} }
func (m *BridgeAsset) String() string { return proto.CompactTextString(m) }
func (*BridgeAsset) ProtoMessage()    {}
func (*BridgeAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b2dec4cec3511ef, []int{0}
}
func (m *BridgeAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BridgeAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BridgeAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BridgeAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BridgeAsset.Merge(m, src)
}
func (m *BridgeAsset) XXX_Size() int {
	return m.Size()
}
func (m *BridgeAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_BridgeAsset.DiscardUnknown(m)
}

var xxx_messageInfo_BridgeAsset proto.InternalMessageInfo

func (m *BridgeAsset) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

func (m *BridgeAsset) GetDisplaySymbol() string {
	if m != nil {
		return m.DisplaySymbol
	}
	return ""
}

func (m *BridgeAsset) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *BridgeAsset) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *BridgeAsset) GetSource() BridgeSource {
	if m != nil {
		return m.Source
	}
	return BridgeSource_BRIDGE_SOURCE_UNSPECIFIED
}

func (m *BridgeAsset) GetSourceChainId() string {
	if m != nil {
		return m.SourceChainId
	}
	return ""
}

func (m *BridgeAsset) GetSourceDenom() string {
	if m != nil {
		return m.SourceDenom
	}
	return ""
}

func (m *BridgeAsset) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *BridgeAsset) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *BridgeAsset) GetRegisteredHeight() int64 {
	if m != nil {
		return m.RegisteredHeight
	}
	return 0
}

func (m *BridgeAsset) GetUpdatedHeight() int64 {
	if m != nil {
		return m.UpdatedHeight
	}
	return 0
}

func init() {
	proto.RegisterEnum("ltrstchain.bridge.BridgeSource", BridgeSource_name, BridgeSource_value)
	proto.RegisterType((*BridgeAsset)(nil), "ltrstchain.bridge.BridgeAsset")
}

func init() { proto.RegisterFile("ltrstchain/bridge/bridge.proto", fileDescriptor_2b2dec4cec3511ef) }

var fileDescriptor_2b2dec4cec3511ef = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0x87, 0xb3, 0x4d, 0x08, 0xc9, 0xa4, 0x29, 0xce, 0x52, 0x51, 0x37, 0x55, 0xdd, 0x80, 0x04,
	0xb2, 0x40, 0x4a, 0x24, 0x7a, 0x40, 0xe2, 0x16, 0x27, 0x86, 0x58, 0x0a, 0x31, 0xda, 0x50, 0x81,
	0xb8, 0x58, 0xb6, 0x77, 0x71, 0x56, 0xf2, 0x9f, 0xc8, 0x76, 0x11, 0x79, 0x0b, 0xae, 0xdc, 0xb8,
	0xf2, 0x26, 0x1c, 0x7b, 0xe4, 0x88, 0x92, 0x0b, 0x8f, 0x81, 0xbc, 0xeb, 0x36, 0x8d, 0x7a, 0x49,
	0x66, 0xbe, 0xdf, 0x67, 0x6b, 0xc6, 0x1a, 0xd0, 0xc2, 0x3c, 0xcd, 0x72, 0x7f, 0xe1, 0xf2, 0x78,
	0xe0, 0xa5, 0x9c, 0x06, 0xac, 0xfc, 0xeb, 0x2f, 0xd3, 0x24, 0x4f, 0x70, 0x67, 0x9b, 0xf7, 0x65,
	0xd0, 0xed, 0xb8, 0x11, 0x8f, 0x93, 0x81, 0xf8, 0x95, 0x56, 0xf7, 0x30, 0x48, 0x82, 0x44, 0x94,
	0x83, 0xa2, 0x92, 0xf4, 0xc9, 0xaf, 0x2a, 0xb4, 0x0c, 0xf1, 0xcc, 0x30, 0xcb, 0x58, 0x8e, 0x4f,
	0xa0, 0xc9, 0x3d, 0xdf, 0xa1, 0x2c, 0x4e, 0x22, 0x15, 0xf5, 0x90, 0xde, 0x24, 0x0d, 0xee, 0xf9,
	0xe3, 0xa2, 0xc7, 0x4f, 0xe1, 0x80, 0xf2, 0x6c, 0x19, 0xba, 0x2b, 0x27, 0x5b, 0x45, 0x5e, 0x12,
	0xaa, 0x7b, 0xc2, 0x68, 0x97, 0x74, 0x2e, 0x20, 0x7e, 0x0c, 0xfb, 0xd7, 0x5a, 0xec, 0x46, 0x4c,
	0xad, 0x0a, 0xa9, 0x55, 0xb2, 0x99, 0x1b, 0x31, 0xdc, 0x85, 0x06, 0x65, 0x3e, 0x8f, 0xdc, 0x30,
	0x53, 0x6b, 0x3d, 0xa4, 0xb7, 0xc9, 0x4d, 0x8f, 0x5f, 0x41, 0x3d, 0x4b, 0x2e, 0x53, 0x9f, 0xa9,
	0xf7, 0x7a, 0x48, 0x3f, 0x78, 0x79, 0xd6, 0xbf, 0xb3, 0x5f, 0x5f, 0x8e, 0x3c, 0x17, 0x1a, 0x29,
	0x75, 0xfc, 0x0c, 0x1e, 0xc8, 0xca, 0x11, 0xae, 0xc3, 0xa9, 0x5a, 0x97, 0xf3, 0x49, 0x3c, 0x2a,
	0xa8, 0x45, 0x8b, 0xf9, 0x4a, 0x4f, 0xae, 0x79, 0x5f, 0xce, 0x27, 0x99, 0xdc, 0xf4, 0x14, 0xc0,
	0x5f, 0xb8, 0x71, 0xcc, 0xc2, 0xe2, 0x2d, 0x0d, 0x21, 0x34, 0x4b, 0x62, 0xd1, 0x62, 0xfc, 0xaf,
	0x2c, 0xe5, 0x5f, 0x38, 0xa3, 0x6a, 0xb3, 0x87, 0xf4, 0x06, 0xb9, 0xe9, 0xf1, 0x0b, 0xe8, 0xa4,
	0x2c, 0xe0, 0x59, 0xce, 0x52, 0x46, 0x9d, 0x05, 0xe3, 0xc1, 0x22, 0x57, 0xa1, 0x87, 0xf4, 0x2a,
	0x51, 0xb6, 0xc1, 0x44, 0xf0, 0xe2, 0x8b, 0x5e, 0x2e, 0xa9, 0x9b, 0x6f, 0xcd, 0x96, 0x30, 0xdb,
	0x25, 0x95, 0xda, 0xeb, 0xda, 0xbf, 0x9f, 0x67, 0xe8, 0xf9, 0x0f, 0x04, 0xfb, 0xb7, 0x17, 0xc7,
	0xa7, 0x70, 0x6c, 0x10, 0x6b, 0xfc, 0xd6, 0x74, 0xe6, 0xf6, 0x05, 0x19, 0x99, 0xce, 0xc5, 0x6c,
	0xfe, 0xde, 0x1c, 0x59, 0x6f, 0x2c, 0x73, 0xac, 0x54, 0xf0, 0x11, 0x3c, 0xdc, 0x8d, 0x67, 0xb6,
	0x31, 0x35, 0x15, 0x84, 0x55, 0x38, 0xdc, 0x0d, 0x86, 0x9f, 0xcc, 0xe9, 0x90, 0x28, 0x7b, 0xb8,
	0x0b, 0x8f, 0x76, 0x93, 0x8f, 0x36, 0x79, 0x37, 0xb1, 0xa7, 0xa6, 0x52, 0xc5, 0x27, 0x70, 0xb4,
	0x9b, 0x59, 0xc6, 0xc8, 0xb1, 0x3f, 0x4c, 0x4c, 0xa2, 0xd4, 0x8c, 0xf3, 0xdf, 0x6b, 0x0d, 0x5d,
	0xad, 0x35, 0xf4, 0x77, 0xad, 0xa1, 0xef, 0x1b, 0xad, 0x72, 0xb5, 0xd1, 0x2a, 0x7f, 0x36, 0x5a,
	0xe5, 0xf3, 0xf1, 0xad, 0xeb, 0xfd, 0x76, 0x7d, 0xbf, 0xf9, 0x6a, 0xc9, 0x32, 0xaf, 0x2e, 0x6e,
	0xf0, 0xfc, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x47, 0x37, 0x82, 0xe1, 0x02, 0x00, 0x00,
}

func (this *BridgeAsset) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*BridgeAsset)
	if !ok {
		that2, ok := that.(BridgeAsset)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.IbcDenom != that1.IbcDenom {
		return false
	}
	if this.DisplaySymbol != that1.DisplaySymbol {
		return false
	}
	if this.DisplayName != that1.DisplayName {
		return false
	}
	if this.Decimals != that1.Decimals {
		return false
	}
	if this.Source != that1.Source {
		return false
	}
	if this.SourceChainId != that1.SourceChainId {
		return false
	}
	if this.SourceDenom != that1.SourceDenom {
		return false
	}
	if this.ChannelId != that1.ChannelId {
		return false
	}
	if this.Verified != that1.Verified {
		return false
	}
	if this.RegisteredHeight != that1.RegisteredHeight {
		return false
	}
	if this.UpdatedHeight != that1.UpdatedHeight {
		return false
	}
	return true
}
func (m *BridgeAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BridgeAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BridgeAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UpdatedHeight != 0 {
		i = encodeVarintBridge(dAtA, i, uint64(m.UpdatedHeight))
		i--
		dAtA[i] = 0x58
	}
	if m.RegisteredHeight != 0 {
		i = encodeVarintBridge(dAtA, i, uint64(m.RegisteredHeight))
		i--
		dAtA[i] = 0x50
	}
	if m.Verified {
		i--
		if m.Verified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SourceDenom) > 0 {
		i -= len(m.SourceDenom)
		copy(dAtA[i:], m.SourceDenom)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.SourceDenom)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SourceChainId) > 0 {
		i -= len(m.SourceChainId)
		copy(dAtA[i:], m.SourceChainId)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.SourceChainId)))
		i--
		dAtA[i] = 0x32
	}
	if m.Source != 0 {
		i = encodeVarintBridge(dAtA, i, uint64(m.Source))
		i--
		dAtA[i] = 0x28
	}
	if m.Decimals != 0 {
		i = encodeVarintBridge(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x20
	}
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.DisplaySymbol) > 0 {
		i -= len(m.DisplaySymbol)
		copy(dAtA[i:], m.DisplaySymbol)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.DisplaySymbol)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.IbcDenom) > 0 {
		i -= len(m.IbcDenom)
		copy(dAtA[i:], m.IbcDenom)
		i = encodeVarintBridge(dAtA, i, uint64(len(m.IbcDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintBridge(dAtA []byte, offset int, v uint64) int {
	offset -= sovBridge(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BridgeAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IbcDenom)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	l = len(m.DisplaySymbol)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	if m.Decimals != 0 {
		n += 1 + sovBridge(uint64(m.Decimals))
	}
	if m.Source != 0 {
		n += 1 + sovBridge(uint64(m.Source))
	}
	l = len(m.SourceChainId)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	l = len(m.SourceDenom)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovBridge(uint64(l))
	}
	if m.Verified {
		n += 2
	}
	if m.RegisteredHeight != 0 {
		n += 1 + sovBridge(uint64(m.RegisteredHeight))
	}
	if m.UpdatedHeight != 0 {
		n += 1 + sovBridge(uint64(m.UpdatedHeight))
	}
	return n
}

func sovBridge(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBridge(x uint64) (n int) {
	return sovBridge(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BridgeAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BridgeAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BridgeAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplaySymbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplaySymbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			m.Source = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Source |= BridgeSource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBridge
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBridge
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Verified = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegisteredHeight", wireType)
			}
			m.RegisteredHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegisteredHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
			}
			m.UpdatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBridge(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBridge
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBridge(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBridge
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBridge
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBridge
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBridge
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBridge
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBridge        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBridge          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBridge = fmt.Errorf("proto: unexpected end of group")
)
