// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ltrstchain/bridge/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ddfde43781644f, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ddfde43781644f, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryBridgeAssetRequest struct {
	IbcDenom string `protobuf:"bytes,1,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
}

func (m *QueryBridgeAssetRequest) Reset()         { *m = QueryBridgeAssetRequest{} }
func (m *QueryBridgeAssetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBridgeAssetRequest) ProtoMessage()    {}
func (*QueryBridgeAssetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ddfde43781644f, []int{2}
}
func (m *QueryBridgeAssetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBridgeAssetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBridgeAssetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBridgeAssetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBridgeAssetRequest.Merge(m, src)
}
func (m *QueryBridgeAssetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBridgeAssetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBridgeAssetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBridgeAssetRequest proto.InternalMessageInfo

func (m *QueryBridgeAssetRequest) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

type QueryBridgeAssetResponse struct {
	Asset BridgeAsset `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset"`
}

func (m *QueryBridgeAssetResponse) Reset()         { *m = QueryBridgeAssetResponse{} }
func (m *QueryBridgeAssetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBridgeAssetResponse) ProtoMessage()    {}
func (*QueryBridgeAssetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ddfde43781644f, []int{3}
}
func (m *QueryBridgeAssetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBridgeAssetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBridgeAssetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBridgeAssetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBridgeAssetResponse.Merge(m, src)
}
func (m *QueryBridgeAssetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBridgeAssetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBridgeAssetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBridgeAssetResponse proto.InternalMessageInfo

func (m *QueryBridgeAssetResponse) GetAsset() BridgeAsset {
	if m != nil {
		return m.Asset
	}
	return BridgeAsset{}
}

type QueryBridgeAssetsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Optional filter by BridgeSource. Pass
	// BRIDGE_SOURCE_UNSPECIFIED to mean "any".
	SourceFilter BridgeSource `protobuf:"varint,2,opt,name=source_filter,json=sourceFilter,proto3,enum=ltrstchain.bridge.BridgeSource" json:"source_filter,omitempty"`
	// Optional filter to only return verified assets.
	VerifiedOnly bool `protobuf:"varint,3,opt,name=verified_only,json=verifiedOnly,proto3" json:"verified_only,omitempty"`
}

func (m *QueryBridgeAssetsRequest) Reset()         { *m = QueryBridgeAssetsRequest{} }
func (m *QueryBridgeAssetsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryBridgeAssetsRequest) ProtoMessage()    {}
func (*QueryBridgeAssetsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ddfde43781644f, []int{4}
}
func (m *QueryBridgeAssetsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBridgeAssetsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBridgeAssetsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBridgeAssetsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBridgeAssetsRequest.Merge(m, src)
}
func (m *QueryBridgeAssetsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryBridgeAssetsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBridgeAssetsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBridgeAssetsRequest proto.InternalMessageInfo

func (m *QueryBridgeAssetsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *QueryBridgeAssetsRequest) GetSourceFilter() BridgeSource {
	if m != nil {
		return m.SourceFilter
	}
	return BridgeSource_BRIDGE_SOURCE_UNSPECIFIED
}

func (m *QueryBridgeAssetsRequest) GetVerifiedOnly() bool {
	if m != nil {
		return m.VerifiedOnly
	}
	return false
}

type QueryBridgeAssetsResponse struct {
	Assets     []BridgeAsset       `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryBridgeAssetsResponse) Reset()         { *m = QueryBridgeAssetsResponse{} }
func (m *QueryBridgeAssetsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryBridgeAssetsResponse) ProtoMessage()    {}
func (*QueryBridgeAssetsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7ddfde43781644f, []int{5}
}
func (m *QueryBridgeAssetsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryBridgeAssetsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryBridgeAssetsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryBridgeAssetsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryBridgeAssetsResponse.Merge(m, src)
}
func (m *QueryBridgeAssetsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryBridgeAssetsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryBridgeAssetsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryBridgeAssetsResponse proto.InternalMessageInfo

func (m *QueryBridgeAssetsResponse) GetAssets() []BridgeAsset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *QueryBridgeAssetsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "ltrstchain.bridge.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "ltrstchain.bridge.QueryParamsResponse")
	proto.RegisterType((*QueryBridgeAssetRequest)(nil), "ltrstchain.bridge.QueryBridgeAssetRequest")
	proto.RegisterType((*QueryBridgeAssetResponse)(nil), "ltrstchain.bridge.QueryBridgeAssetResponse")
	proto.RegisterType((*QueryBridgeAssetsRequest)(nil), "ltrstchain.bridge.QueryBridgeAssetsRequest")
	proto.RegisterType((*QueryBridgeAssetsResponse)(nil), "ltrstchain.bridge.QueryBridgeAssetsResponse")
}

func init() { proto.RegisterFile("ltrstchain/bridge/query.proto", fileDescriptor_d7ddfde43781644f) }

var fileDescriptor_d7ddfde43781644f = []byte{
	// 557 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x41, 0x6b, 0x13, 0x41,
	0x14, 0xce, 0x24, 0x36, 0xb4, 0xd3, 0x54, 0xe8, 0x58, 0x30, 0x49, 0x75, 0x1b, 0x57, 0xda, 0x86,
	0xaa, 0x3b, 0x34, 0x05, 0x05, 0xf1, 0x62, 0x28, 0xf5, 0xa6, 0x75, 0x05, 0x0f, 0x5e, 0xc2, 0x6c,
	0x32, 0x5d, 0x07, 0x92, 0x99, 0xed, 0xce, 0xa4, 0x18, 0xc5, 0x8b, 0x67, 0x0f, 0x82, 0xf8, 0x07,
	0x3c, 0xfa, 0x4b, 0x7a, 0x11, 0x0a, 0x5e, 0x3c, 0x89, 0x24, 0xfe, 0x10, 0xd9, 0x99, 0x49, 0xbb,
	0x65, 0x13, 0xba, 0x97, 0x64, 0xf2, 0xde, 0xf7, 0xbd, 0xf7, 0xbd, 0xef, 0x3d, 0x02, 0x6f, 0xf7,
	0x55, 0x2c, 0x55, 0xf7, 0x2d, 0x61, 0x1c, 0x07, 0x31, 0xeb, 0x85, 0x14, 0x1f, 0x0f, 0x69, 0x3c,
	0xf2, 0xa2, 0x58, 0x28, 0x81, 0x56, 0x2f, 0xd2, 0x9e, 0x49, 0xd7, 0x57, 0xc9, 0x80, 0x71, 0x81,
	0xf5, 0xa7, 0x41, 0xd5, 0x77, 0xba, 0x42, 0x0e, 0x84, 0xc4, 0x01, 0x91, 0x96, 0x8e, 0x4f, 0x76,
	0x03, 0xaa, 0xc8, 0x2e, 0x8e, 0x48, 0xc8, 0x38, 0x51, 0x4c, 0x70, 0x8b, 0x5d, 0x0b, 0x45, 0x28,
	0xf4, 0x13, 0x27, 0x2f, 0x1b, 0xbd, 0x15, 0x0a, 0x11, 0xf6, 0x29, 0x26, 0x11, 0xc3, 0x84, 0x73,
	0xa1, 0x34, 0x45, 0xda, 0xac, 0x93, 0x15, 0x69, 0xbe, 0xe6, 0xe7, 0x23, 0x12, 0x93, 0x81, 0xe5,
	0xbb, 0x6b, 0x10, 0xbd, 0x4c, 0x54, 0x1d, 0xea, 0xa0, 0x4f, 0x8f, 0x87, 0x54, 0x2a, 0xf7, 0x39,
	0xbc, 0x71, 0x29, 0x2a, 0x23, 0xc1, 0x25, 0x45, 0x8f, 0x60, 0xd9, 0x90, 0xab, 0xa0, 0x01, 0x9a,
	0xcb, 0xad, 0x9a, 0x97, 0xf1, 0xc0, 0x33, 0x94, 0xf6, 0xb5, 0xd3, 0x3f, 0x1b, 0x05, 0xdf, 0xc2,
	0xdd, 0x87, 0xf0, 0xa6, 0xae, 0xd7, 0xd6, 0x98, 0xa7, 0x52, 0x52, 0x65, 0x5b, 0xa1, 0x75, 0xb8,
	0xc4, 0x82, 0x6e, 0xa7, 0x47, 0xb9, 0x18, 0xe8, 0xb2, 0x4b, 0xfe, 0x22, 0x0b, 0xba, 0xfb, 0xc9,
	0x6f, 0xf7, 0x35, 0xac, 0x66, 0x79, 0x56, 0xcc, 0x63, 0xb8, 0x40, 0x92, 0x80, 0xd5, 0xe2, 0xcc,
	0xd0, 0x92, 0xa2, 0x59, 0x41, 0x86, 0xe2, 0xfe, 0x04, 0xd9, 0xc2, 0xd3, 0xe1, 0xd1, 0x01, 0x84,
	0x17, 0xab, 0xb1, 0xd5, 0xb7, 0x3c, 0xb3, 0x47, 0x2f, 0xd9, 0xa3, 0x67, 0xce, 0xc0, 0xee, 0xd1,
	0x3b, 0x24, 0x21, 0xb5, 0x5c, 0x3f, 0xc5, 0x44, 0xfb, 0x70, 0x45, 0x8a, 0x61, 0xdc, 0xa5, 0x9d,
	0x23, 0xd6, 0x57, 0x34, 0xae, 0x16, 0x1b, 0xa0, 0x79, 0xbd, 0xb5, 0x31, 0x57, 0xe8, 0x2b, 0x8d,
	0xf6, 0x2b, 0x86, 0x75, 0xa0, 0x49, 0xe8, 0x2e, 0x5c, 0x39, 0xa1, 0x31, 0x3b, 0x62, 0xb4, 0xd7,
	0x11, 0xbc, 0x3f, 0xaa, 0x96, 0x1a, 0xa0, 0xb9, 0xe8, 0x57, 0xa6, 0xc1, 0x17, 0xbc, 0x3f, 0x72,
	0xbf, 0x03, 0x58, 0x9b, 0x31, 0x8f, 0x75, 0xea, 0x09, 0x2c, 0xeb, 0xb1, 0x93, 0xb5, 0x95, 0x72,
	0x5b, 0x65, 0x39, 0xe8, 0xd9, 0x25, 0x3b, 0x8a, 0xda, 0x8e, 0xed, 0x2b, 0xed, 0x30, 0xad, 0xd3,
	0x7e, 0xb4, 0x7e, 0x94, 0xe0, 0x82, 0x16, 0x89, 0xde, 0xc3, 0xb2, 0x39, 0x13, 0xb4, 0x39, 0x43,
	0x4a, 0xf6, 0x1e, 0xeb, 0x5b, 0x57, 0xc1, 0x4c, 0x3b, 0xf7, 0xce, 0xa7, 0x5f, 0xff, 0xbe, 0x16,
	0xd7, 0x51, 0x0d, 0xcf, 0x3b, 0x7b, 0xf4, 0x0d, 0xc0, 0xe5, 0xd4, 0xb0, 0x68, 0x67, 0x5e, 0xe9,
	0xec, 0xad, 0xd6, 0xef, 0xe5, 0xc2, 0x5a, 0x2d, 0x0f, 0xb4, 0x96, 0x6d, 0xb4, 0x39, 0x43, 0x8b,
	0xb1, 0x16, 0x7f, 0x38, 0xbf, 0xfc, 0x8f, 0xe8, 0x33, 0x80, 0x95, 0xf4, 0xf6, 0x50, 0x9e, 0x66,
	0xe7, 0x06, 0xdd, 0xcf, 0x07, 0xce, 0x61, 0x93, 0x91, 0xd6, 0xde, 0x3b, 0x1d, 0x3b, 0xe0, 0x6c,
	0xec, 0x80, 0xbf, 0x63, 0x07, 0x7c, 0x99, 0x38, 0x85, 0xb3, 0x89, 0x53, 0xf8, 0x3d, 0x71, 0x0a,
	0x6f, 0x6a, 0x29, 0xce, 0xbb, 0x29, 0x4b, 0x8d, 0x22, 0x2a, 0x83, 0xb2, 0xfe, 0x4f, 0xd9, 0xfb,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0x06, 0x06, 0x31, 0xa5, 0x3a, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params returns the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// BridgeAsset fetches a single asset by its ibc_denom. 404 if not
	// registered.
	BridgeAsset(ctx context.Context, in *QueryBridgeAssetRequest, opts ...grpc.CallOption) (*QueryBridgeAssetResponse, error)
	// BridgeAssets lists all registered assets, paginated.
	BridgeAssets(ctx context.Context, in *QueryBridgeAssetsRequest, opts ...grpc.CallOption) (*QueryBridgeAssetsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.bridge.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BridgeAsset(ctx context.Context, in *QueryBridgeAssetRequest, opts ...grpc.CallOption) (*QueryBridgeAssetResponse, error) {
	out := new(QueryBridgeAssetResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.bridge.Query/BridgeAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BridgeAssets(ctx context.Context, in *QueryBridgeAssetsRequest, opts ...grpc.CallOption) (*QueryBridgeAssetsResponse, error) {
	out := new(QueryBridgeAssetsResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.bridge.Query/BridgeAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params returns the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// BridgeAsset fetches a single asset by its ibc_denom. 404 if not
	// registered.
	BridgeAsset(context.Context, *QueryBridgeAssetRequest) (*QueryBridgeAssetResponse, error)
	// BridgeAssets lists all registered assets, paginated.
	BridgeAssets(context.Context, *QueryBridgeAssetsRequest) (*QueryBridgeAssetsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) BridgeAsset(ctx context.Context, req *QueryBridgeAssetRequest) (*QueryBridgeAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeAsset not implemented")
}
func (*UnimplementedQueryServer) BridgeAssets(ctx context.Context, req *QueryBridgeAssetsRequest) (*QueryBridgeAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BridgeAssets not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.bridge.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BridgeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBridgeAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BridgeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.bridge.Query/BridgeAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BridgeAsset(ctx, req.(*QueryBridgeAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BridgeAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBridgeAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BridgeAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.bridge.Query/BridgeAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BridgeAssets(ctx, req.(*QueryBridgeAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ltrstchain.bridge.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "BridgeAsset",
			Handler:    _Query_BridgeAsset_Handler,
		},
		{
			MethodName: "BridgeAssets",
			Handler:    _Query_BridgeAssets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ltrstchain/bridge/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBridgeAssetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBridgeAssetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBridgeAssetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IbcDenom) > 0 {
		i -= len(m.IbcDenom)
		copy(dAtA[i:], m.IbcDenom)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.IbcDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBridgeAssetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBridgeAssetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBridgeAssetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Asset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryBridgeAssetsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBridgeAssetsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBridgeAssetsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VerifiedOnly {
		i--
		if m.VerifiedOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.SourceFilter != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SourceFilter))
		i--
		dAtA[i] = 0x10
	}
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryBridgeAssetsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryBridgeAssetsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryBridgeAssetsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Assets) > 0 {
		for iNdEx := len(m.Assets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBridgeAssetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IbcDenom)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryBridgeAssetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Asset.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryBridgeAssetsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.SourceFilter != 0 {
		n += 1 + sovQuery(uint64(m.SourceFilter))
	}
	if m.VerifiedOnly {
		n += 2
	}
	return n
}

func (m *QueryBridgeAssetsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Assets) > 0 {
		for _, e := range m.Assets {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBridgeAssetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBridgeAssetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBridgeAssetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBridgeAssetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBridgeAssetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBridgeAssetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBridgeAssetsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBridgeAssetsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBridgeAssetsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceFilter", wireType)
			}
			m.SourceFilter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceFilter |= BridgeSource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifiedOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.VerifiedOnly = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryBridgeAssetsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryBridgeAssetsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryBridgeAssetsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assets = append(m.Assets, BridgeAsset{})
			if err := m.Assets[len(m.Assets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
