// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ltrstchain/bridge/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8570fb721657e5, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8570fb721657e5, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgRegisterBridgeAsset struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// asset holds every field of the new BridgeAsset record.
	Asset BridgeAsset `protobuf:"bytes,2,opt,name=asset,proto3" json:"asset"`
}

func (m *MsgRegisterBridgeAsset) Reset()         { *m = MsgRegisterBridgeAsset{} }
func (m *MsgRegisterBridgeAsset) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterBridgeAsset) ProtoMessage()    {}
func (*MsgRegisterBridgeAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8570fb721657e5, []int{2}
}
func (m *MsgRegisterBridgeAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterBridgeAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterBridgeAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterBridgeAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterBridgeAsset.Merge(m, src)
}
func (m *MsgRegisterBridgeAsset) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterBridgeAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterBridgeAsset.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterBridgeAsset proto.InternalMessageInfo

func (m *MsgRegisterBridgeAsset) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRegisterBridgeAsset) GetAsset() BridgeAsset {
	if m != nil {
		return m.Asset
	}
	return BridgeAsset{}
}

type MsgRegisterBridgeAssetResponse struct {
}

func (m *MsgRegisterBridgeAssetResponse) Reset()         { *m = MsgRegisterBridgeAssetResponse{} }
func (m *MsgRegisterBridgeAssetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRegisterBridgeAssetResponse) ProtoMessage()    {}
func (*MsgRegisterBridgeAssetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8570fb721657e5, []int{3}
}
func (m *MsgRegisterBridgeAssetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRegisterBridgeAssetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRegisterBridgeAssetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRegisterBridgeAssetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRegisterBridgeAssetResponse.Merge(m, src)
}
func (m *MsgRegisterBridgeAssetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRegisterBridgeAssetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRegisterBridgeAssetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRegisterBridgeAssetResponse proto.InternalMessageInfo

type MsgUpdateBridgeAsset struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// ibc_denom identifies the existing record.
	IbcDenom string `protobuf:"bytes,2,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	// Fields that may be mutated. Leave empty to keep the existing
	// value unchanged — the keeper treats empty strings as "no
	// change".
	DisplaySymbol string       `protobuf:"bytes,3,opt,name=display_symbol,json=displaySymbol,proto3" json:"display_symbol,omitempty"`
	DisplayName   string       `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Decimals      uint32       `protobuf:"varint,5,opt,name=decimals,proto3" json:"decimals,omitempty"`
	SetDecimals   bool         `protobuf:"varint,6,opt,name=set_decimals,json=setDecimals,proto3" json:"set_decimals,omitempty"`
	Source        BridgeSource `protobuf:"varint,7,opt,name=source,proto3,enum=ltrstchain.bridge.BridgeSource" json:"source,omitempty"`
	SetSource     bool         `protobuf:"varint,8,opt,name=set_source,json=setSource,proto3" json:"set_source,omitempty"`
	SourceChainId string       `protobuf:"bytes,9,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"`
	SourceDenom   string       `protobuf:"bytes,10,opt,name=source_denom,json=sourceDenom,proto3" json:"source_denom,omitempty"`
	ChannelId     string       `protobuf:"bytes,11,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Verified      bool         `protobuf:"varint,12,opt,name=verified,proto3" json:"verified,omitempty"`
	SetVerified   bool         `protobuf:"varint,13,opt,name=set_verified,json=setVerified,proto3" json:"set_verified,omitempty"`
}

func (m *MsgUpdateBridgeAsset) Reset()         { *m = MsgUpdateBridgeAsset{} }
func (m *MsgUpdateBridgeAsset) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBridgeAsset) ProtoMessage()    {}
func (*MsgUpdateBridgeAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8570fb721657e5, []int{4}
}
func (m *MsgUpdateBridgeAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBridgeAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBridgeAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBridgeAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBridgeAsset.Merge(m, src)
}
func (m *MsgUpdateBridgeAsset) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBridgeAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBridgeAsset.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBridgeAsset proto.InternalMessageInfo

func (m *MsgUpdateBridgeAsset) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateBridgeAsset) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

func (m *MsgUpdateBridgeAsset) GetDisplaySymbol() string {
	if m != nil {
		return m.DisplaySymbol
	}
	return ""
}

func (m *MsgUpdateBridgeAsset) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *MsgUpdateBridgeAsset) GetDecimals() uint32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *MsgUpdateBridgeAsset) GetSetDecimals() bool {
	if m != nil {
		return m.SetDecimals
	}
	return false
}

func (m *MsgUpdateBridgeAsset) GetSource() BridgeSource {
	if m != nil {
		return m.Source
	}
	return BridgeSource_BRIDGE_SOURCE_UNSPECIFIED
}

func (m *MsgUpdateBridgeAsset) GetSetSource() bool {
	if m != nil {
		return m.SetSource
	}
	return false
}

func (m *MsgUpdateBridgeAsset) GetSourceChainId() string {
	if m != nil {
		return m.SourceChainId
	}
	return ""
}

func (m *MsgUpdateBridgeAsset) GetSourceDenom() string {
	if m != nil {
		return m.SourceDenom
	}
	return ""
}

func (m *MsgUpdateBridgeAsset) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *MsgUpdateBridgeAsset) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

func (m *MsgUpdateBridgeAsset) GetSetVerified() bool {
	if m != nil {
		return m.SetVerified
	}
	return false
}

type MsgUpdateBridgeAssetResponse struct {
}

func (m *MsgUpdateBridgeAssetResponse) Reset()         { *m = MsgUpdateBridgeAssetResponse{} }
func (m *MsgUpdateBridgeAssetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBridgeAssetResponse) ProtoMessage()    {}
func (*MsgUpdateBridgeAssetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8570fb721657e5, []int{5}
}
func (m *MsgUpdateBridgeAssetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBridgeAssetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBridgeAssetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBridgeAssetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBridgeAssetResponse.Merge(m, src)
}
func (m *MsgUpdateBridgeAssetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBridgeAssetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBridgeAssetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBridgeAssetResponse proto.InternalMessageInfo

type MsgRemoveBridgeAsset struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	IbcDenom  string `protobuf:"bytes,2,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
}

func (m *MsgRemoveBridgeAsset) Reset()         { *m = MsgRemoveBridgeAsset{} }
func (m *MsgRemoveBridgeAsset) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveBridgeAsset) ProtoMessage()    {}
func (*MsgRemoveBridgeAsset) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8570fb721657e5, []int{6}
}
func (m *MsgRemoveBridgeAsset) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveBridgeAsset) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveBridgeAsset.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveBridgeAsset) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveBridgeAsset.Merge(m, src)
}
func (m *MsgRemoveBridgeAsset) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveBridgeAsset) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveBridgeAsset.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveBridgeAsset proto.InternalMessageInfo

func (m *MsgRemoveBridgeAsset) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgRemoveBridgeAsset) GetIbcDenom() string {
	if m != nil {
		return m.IbcDenom
	}
	return ""
}

type MsgRemoveBridgeAssetResponse struct {
}

func (m *MsgRemoveBridgeAssetResponse) Reset()         { *m = MsgRemoveBridgeAssetResponse{} }
func (m *MsgRemoveBridgeAssetResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRemoveBridgeAssetResponse) ProtoMessage()    {}
func (*MsgRemoveBridgeAssetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c8570fb721657e5, []int{7}
}
func (m *MsgRemoveBridgeAssetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRemoveBridgeAssetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRemoveBridgeAssetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRemoveBridgeAssetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRemoveBridgeAssetResponse.Merge(m, src)
}
func (m *MsgRemoveBridgeAssetResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRemoveBridgeAssetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRemoveBridgeAssetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRemoveBridgeAssetResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "ltrstchain.bridge.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "ltrstchain.bridge.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgRegisterBridgeAsset)(nil), "ltrstchain.bridge.MsgRegisterBridgeAsset")
	proto.RegisterType((*MsgRegisterBridgeAssetResponse)(nil), "ltrstchain.bridge.MsgRegisterBridgeAssetResponse")
	proto.RegisterType((*MsgUpdateBridgeAsset)(nil), "ltrstchain.bridge.MsgUpdateBridgeAsset")
	proto.RegisterType((*MsgUpdateBridgeAssetResponse)(nil), "ltrstchain.bridge.MsgUpdateBridgeAssetResponse")
	proto.RegisterType((*MsgRemoveBridgeAsset)(nil), "ltrstchain.bridge.MsgRemoveBridgeAsset")
	proto.RegisterType((*MsgRemoveBridgeAssetResponse)(nil), "ltrstchain.bridge.MsgRemoveBridgeAssetResponse")
}

func init() { proto.RegisterFile("ltrstchain/bridge/tx.proto", fileDescriptor_2c8570fb721657e5) }

var fileDescriptor_2c8570fb721657e5 = []byte{
	// 703 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x3f, 0x6f, 0xd3, 0x5e,
	0x14, 0x8d, 0x7f, 0x6d, 0xf3, 0x8b, 0x6f, 0xfa, 0x47, 0x35, 0x15, 0x75, 0x0c, 0x75, 0x43, 0x10,
	0x34, 0x44, 0x22, 0x56, 0x5b, 0xa9, 0x95, 0x82, 0x18, 0x1a, 0xba, 0x74, 0x28, 0x42, 0xae, 0x60,
	0x60, 0x20, 0x72, 0xec, 0x87, 0xfb, 0xa4, 0xd8, 0x2f, 0xf2, 0x7b, 0xad, 0x9a, 0x0d, 0x31, 0x32,
	0xf1, 0x31, 0x18, 0x2b, 0xc4, 0xc4, 0xc2, 0x5a, 0x89, 0xa5, 0x62, 0x62, 0x42, 0xa8, 0x1d, 0xfa,
	0x35, 0x90, 0xdf, 0x7b, 0x71, 0x42, 0xec, 0x94, 0x82, 0x60, 0xa9, 0xfb, 0xce, 0x39, 0xbe, 0xf7,
	0x9c, 0xeb, 0x6b, 0x07, 0x8c, 0x0e, 0x8b, 0x28, 0x73, 0xf7, 0x1d, 0x1c, 0x5a, 0xed, 0x08, 0x7b,
	0x3e, 0xb2, 0xd8, 0x51, 0xbd, 0x1b, 0x11, 0x46, 0xb4, 0xf9, 0x01, 0x57, 0x17, 0x9c, 0x31, 0xef,
	0x04, 0x38, 0x24, 0x16, 0xff, 0x2b, 0x54, 0xc6, 0xa2, 0x4b, 0x68, 0x40, 0xa8, 0x15, 0x50, 0xdf,
	0x3a, 0x5c, 0x8d, 0x2f, 0x92, 0x28, 0x09, 0xa2, 0xc5, 0x4f, 0x96, 0x38, 0x48, 0x6a, 0xc1, 0x27,
	0x3e, 0x11, 0x78, 0xfc, 0x9f, 0x44, 0xcd, 0xb4, 0x17, 0x71, 0x19, 0xcf, 0x77, 0x9d, 0xc8, 0x09,
	0x64, 0xd5, 0xca, 0x47, 0x05, 0xe6, 0x76, 0xa9, 0xff, 0xb4, 0xeb, 0x39, 0x0c, 0x3d, 0xe1, 0x8c,
	0xb6, 0x01, 0xaa, 0x73, 0xc0, 0xf6, 0x49, 0x84, 0x59, 0x4f, 0x57, 0xca, 0x4a, 0x55, 0x6d, 0xea,
	0x5f, 0x3e, 0xdc, 0x5f, 0x90, 0x76, 0xb6, 0x3c, 0x2f, 0x42, 0x94, 0xee, 0xb1, 0x08, 0x87, 0xbe,
	0x3d, 0x90, 0x6a, 0x9b, 0x90, 0x17, 0xb5, 0xf5, 0xff, 0xca, 0x4a, 0xb5, 0xb8, 0x56, 0xaa, 0xa7,
	0x86, 0x51, 0x17, 0x2d, 0x9a, 0x93, 0x27, 0xdf, 0x96, 0x73, 0xb6, 0x94, 0x37, 0x36, 0x5e, 0x5f,
	0x1c, 0xd7, 0x06, 0x85, 0xde, 0x5c, 0x1c, 0xd7, 0x6e, 0x0f, 0xf9, 0x3e, 0xea, 0x3b, 0x1f, 0x31,
	0x5a, 0x29, 0xc1, 0xe2, 0x08, 0x64, 0x23, 0xda, 0x25, 0x21, 0x45, 0x95, 0xcf, 0x0a, 0x5c, 0xdf,
	0xa5, 0xbe, 0x8d, 0x7c, 0x4c, 0x19, 0x8a, 0x9a, 0xbc, 0xc0, 0x16, 0xa5, 0x88, 0xfd, 0x71, 0xbc,
	0x06, 0x4c, 0x39, 0x71, 0x01, 0x99, 0xce, 0xcc, 0x48, 0x37, 0xd4, 0x46, 0x46, 0x14, 0xb7, 0x34,
	0x1e, 0xa6, 0x13, 0xd6, 0xc6, 0x24, 0xcc, 0xb0, 0x5c, 0x29, 0x83, 0x99, 0xcd, 0x24, 0x79, 0xdf,
	0x4f, 0xc2, 0x42, 0x32, 0x8b, 0xbf, 0x91, 0xf6, 0x06, 0xa8, 0xb8, 0xed, 0xb6, 0x3c, 0x14, 0x92,
	0x80, 0x27, 0x56, 0xed, 0x02, 0x6e, 0xbb, 0xdb, 0xf1, 0x59, 0xbb, 0x03, 0xb3, 0x1e, 0xa6, 0xdd,
	0x8e, 0xd3, 0x6b, 0xd1, 0x5e, 0xd0, 0x26, 0x1d, 0x7d, 0x82, 0x2b, 0x66, 0x24, 0xba, 0xc7, 0x41,
	0xed, 0x16, 0x4c, 0xf7, 0x65, 0xa1, 0x13, 0x20, 0x7d, 0x92, 0x8b, 0x8a, 0x12, 0x7b, 0xec, 0x04,
	0x48, 0x33, 0xa0, 0xe0, 0x21, 0x17, 0x07, 0x4e, 0x87, 0xea, 0x53, 0x65, 0xa5, 0x3a, 0x63, 0x27,
	0xe7, 0xf8, 0x76, 0x8a, 0x58, 0x2b, 0xe1, 0xf3, 0x65, 0xa5, 0x5a, 0xb0, 0x8b, 0x14, 0xb1, 0xed,
	0xbe, 0x64, 0x13, 0xf2, 0x94, 0x1c, 0x44, 0x2e, 0xd2, 0xff, 0x2f, 0x2b, 0xd5, 0xd9, 0xb5, 0xe5,
	0xb1, 0x0f, 0x65, 0x8f, 0xcb, 0x6c, 0x29, 0xd7, 0x96, 0x00, 0xe2, 0xda, 0xf2, 0xe6, 0x02, 0xaf,
	0xac, 0x52, 0xc4, 0x84, 0x4c, 0xbb, 0x0b, 0x73, 0x82, 0x6a, 0xf1, 0x52, 0x2d, 0xec, 0xe9, 0xaa,
	0x48, 0x28, 0xe0, 0x47, 0x31, 0xba, 0xe3, 0x71, 0x8b, 0x42, 0x27, 0x06, 0x05, 0x22, 0xa1, 0xc0,
	0xc4, 0xac, 0x96, 0x00, 0xdc, 0x7d, 0x27, 0x0c, 0x51, 0x27, 0xae, 0x52, 0xe4, 0x02, 0x55, 0x22,
	0x3b, 0x5e, 0x3c, 0x80, 0x43, 0x14, 0xe1, 0x97, 0x18, 0x79, 0xfa, 0x34, 0xb7, 0x91, 0x9c, 0xfb,
	0x03, 0x48, 0xf8, 0x99, 0x64, 0x00, 0xcf, 0x24, 0xd4, 0x78, 0x90, 0x5e, 0xac, 0xea, 0xa5, 0xaf,
	0xce, 0xf0, 0x5a, 0x99, 0x70, 0x33, 0x0b, 0x4f, 0x96, 0xea, 0x9d, 0xc2, 0x97, 0xca, 0x46, 0x01,
	0x39, 0xfc, 0xe7, 0x4b, 0xf5, 0x3b, 0x51, 0x52, 0x8e, 0x64, 0x94, 0x14, 0xde, 0x8f, 0xb2, 0xf6,
	0x69, 0x02, 0x26, 0x76, 0xa9, 0xaf, 0xbd, 0x80, 0xe9, 0x9f, 0xbe, 0x75, 0x95, 0x8c, 0x85, 0x19,
	0xf9, 0xa6, 0x18, 0xb5, 0x5f, 0x6b, 0xfa, 0x7d, 0x34, 0x0a, 0xd7, 0xb2, 0xbe, 0x39, 0xf7, 0xb2,
	0x4b, 0x64, 0x48, 0x8d, 0xd5, 0x2b, 0x4b, 0x93, 0xa6, 0x01, 0xcc, 0xa7, 0x5f, 0xfc, 0x95, 0xcb,
	0x5c, 0x0f, 0x37, 0xb4, 0xae, 0x28, 0x1c, 0x6e, 0x97, 0x5e, 0x89, 0x95, 0x71, 0xb6, 0x47, 0x84,
	0xe3, 0xda, 0x8d, 0x7d, 0x74, 0xc6, 0xd4, 0xab, 0x8b, 0xe3, 0x9a, 0xd2, 0x5c, 0x3f, 0x39, 0x33,
	0x95, 0xd3, 0x33, 0x53, 0xf9, 0x7e, 0x66, 0x2a, 0x6f, 0xcf, 0xcd, 0xdc, 0xe9, 0xb9, 0x99, 0xfb,
	0x7a, 0x6e, 0xe6, 0x9e, 0x97, 0xb2, 0xb6, 0x84, 0xf5, 0xba, 0x88, 0xb6, 0xf3, 0xfc, 0x57, 0x6e,
	0xfd, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x88, 0x62, 0x5a, 0xae, 0xb3, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams changes the module params. Authority-only.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// RegisterBridgeAsset adds a new asset entry. Authority-only by
	// default (Params.require_governance_registration).
	RegisterBridgeAsset(ctx context.Context, in *MsgRegisterBridgeAsset, opts ...grpc.CallOption) (*MsgRegisterBridgeAssetResponse, error)
	// UpdateBridgeAsset mutates display fields and/or verified flag.
	// Authority-only.
	UpdateBridgeAsset(ctx context.Context, in *MsgUpdateBridgeAsset, opts ...grpc.CallOption) (*MsgUpdateBridgeAssetResponse, error)
	// RemoveBridgeAsset deletes an entry. Does not claw back any bank
	// balances — x/bank tokens keep flowing. The entry removal only
	// affects what UIs decide to surface. Authority-only.
	RemoveBridgeAsset(ctx context.Context, in *MsgRemoveBridgeAsset, opts ...grpc.CallOption) (*MsgRemoveBridgeAssetResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.bridge.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterBridgeAsset(ctx context.Context, in *MsgRegisterBridgeAsset, opts ...grpc.CallOption) (*MsgRegisterBridgeAssetResponse, error) {
	out := new(MsgRegisterBridgeAssetResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.bridge.Msg/RegisterBridgeAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateBridgeAsset(ctx context.Context, in *MsgUpdateBridgeAsset, opts ...grpc.CallOption) (*MsgUpdateBridgeAssetResponse, error) {
	out := new(MsgUpdateBridgeAssetResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.bridge.Msg/UpdateBridgeAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveBridgeAsset(ctx context.Context, in *MsgRemoveBridgeAsset, opts ...grpc.CallOption) (*MsgRemoveBridgeAssetResponse, error) {
	out := new(MsgRemoveBridgeAssetResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.bridge.Msg/RemoveBridgeAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams changes the module params. Authority-only.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// RegisterBridgeAsset adds a new asset entry. Authority-only by
	// default (Params.require_governance_registration).
	RegisterBridgeAsset(context.Context, *MsgRegisterBridgeAsset) (*MsgRegisterBridgeAssetResponse, error)
	// UpdateBridgeAsset mutates display fields and/or verified flag.
	// Authority-only.
	UpdateBridgeAsset(context.Context, *MsgUpdateBridgeAsset) (*MsgUpdateBridgeAssetResponse, error)
	// RemoveBridgeAsset deletes an entry. Does not claw back any bank
	// balances — x/bank tokens keep flowing. The entry removal only
	// affects what UIs decide to surface. Authority-only.
	RemoveBridgeAsset(context.Context, *MsgRemoveBridgeAsset) (*MsgRemoveBridgeAssetResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) RegisterBridgeAsset(ctx context.Context, req *MsgRegisterBridgeAsset) (*MsgRegisterBridgeAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBridgeAsset not implemented")
}
func (*UnimplementedMsgServer) UpdateBridgeAsset(ctx context.Context, req *MsgUpdateBridgeAsset) (*MsgUpdateBridgeAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBridgeAsset not implemented")
}
func (*UnimplementedMsgServer) RemoveBridgeAsset(ctx context.Context, req *MsgRemoveBridgeAsset) (*MsgRemoveBridgeAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBridgeAsset not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.bridge.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterBridgeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterBridgeAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterBridgeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.bridge.Msg/RegisterBridgeAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterBridgeAsset(ctx, req.(*MsgRegisterBridgeAsset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateBridgeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateBridgeAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateBridgeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.bridge.Msg/UpdateBridgeAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateBridgeAsset(ctx, req.(*MsgUpdateBridgeAsset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveBridgeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveBridgeAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveBridgeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.bridge.Msg/RemoveBridgeAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveBridgeAsset(ctx, req.(*MsgRemoveBridgeAsset))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ltrstchain.bridge.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterBridgeAsset",
			Handler:    _Msg_RegisterBridgeAsset_Handler,
		},
		{
			MethodName: "UpdateBridgeAsset",
			Handler:    _Msg_UpdateBridgeAsset_Handler,
		},
		{
			MethodName: "RemoveBridgeAsset",
			Handler:    _Msg_RemoveBridgeAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ltrstchain/bridge/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRegisterBridgeAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterBridgeAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterBridgeAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Asset.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRegisterBridgeAssetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRegisterBridgeAssetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRegisterBridgeAssetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBridgeAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBridgeAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBridgeAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SetVerified {
		i--
		if m.SetVerified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.Verified {
		i--
		if m.Verified {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if len(m.ChannelId) > 0 {
		i -= len(m.ChannelId)
		copy(dAtA[i:], m.ChannelId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelId)))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.SourceDenom) > 0 {
		i -= len(m.SourceDenom)
		copy(dAtA[i:], m.SourceDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceDenom)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.SourceChainId) > 0 {
		i -= len(m.SourceChainId)
		copy(dAtA[i:], m.SourceChainId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChainId)))
		i--
		dAtA[i] = 0x4a
	}
	if m.SetSource {
		i--
		if m.SetSource {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.Source != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Source))
		i--
		dAtA[i] = 0x38
	}
	if m.SetDecimals {
		i--
		if m.SetDecimals {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.Decimals != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Decimals))
		i--
		dAtA[i] = 0x28
	}
	if len(m.DisplayName) > 0 {
		i -= len(m.DisplayName)
		copy(dAtA[i:], m.DisplayName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DisplayName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.DisplaySymbol) > 0 {
		i -= len(m.DisplaySymbol)
		copy(dAtA[i:], m.DisplaySymbol)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DisplaySymbol)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.IbcDenom) > 0 {
		i -= len(m.IbcDenom)
		copy(dAtA[i:], m.IbcDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IbcDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBridgeAssetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBridgeAssetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBridgeAssetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgRemoveBridgeAsset) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveBridgeAsset) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveBridgeAsset) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IbcDenom) > 0 {
		i -= len(m.IbcDenom)
		copy(dAtA[i:], m.IbcDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IbcDenom)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRemoveBridgeAssetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRemoveBridgeAssetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRemoveBridgeAssetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRegisterBridgeAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Asset.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgRegisterBridgeAssetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateBridgeAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.IbcDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DisplaySymbol)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DisplayName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Decimals != 0 {
		n += 1 + sovTx(uint64(m.Decimals))
	}
	if m.SetDecimals {
		n += 2
	}
	if m.Source != 0 {
		n += 1 + sovTx(uint64(m.Source))
	}
	if m.SetSource {
		n += 2
	}
	l = len(m.SourceChainId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SourceDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Verified {
		n += 2
	}
	if m.SetVerified {
		n += 2
	}
	return n
}

func (m *MsgUpdateBridgeAssetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgRemoveBridgeAsset) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.IbcDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgRemoveBridgeAssetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterBridgeAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterBridgeAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterBridgeAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Asset", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Asset.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRegisterBridgeAssetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRegisterBridgeAssetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRegisterBridgeAssetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBridgeAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBridgeAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBridgeAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplaySymbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplaySymbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DisplayName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
			}
			m.Decimals = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Decimals |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetDecimals", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SetDecimals = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			m.Source = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Source |= BridgeSource(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetSource", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SetSource = bool(v != 0)
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Verified = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SetVerified", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SetVerified = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBridgeAssetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBridgeAssetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBridgeAssetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveBridgeAsset) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveBridgeAsset: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveBridgeAsset: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRemoveBridgeAssetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRemoveBridgeAssetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRemoveBridgeAssetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
