// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ltrstchain/ltrstdex/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for x/ltrstdex.
type Params struct {
	// max_open_orders_per_account caps how many live (non-filled,
	// non-cancelled) orders a single address may hold across all
	// markets. Prevents state bloat from spammers without requiring a
	// per-order escrow.
	MaxOpenOrdersPerAccount uint32 `protobuf:"varint,1,opt,name=max_open_orders_per_account,json=maxOpenOrdersPerAccount,proto3" json:"max_open_orders_per_account,omitempty"`
	// gov_only_market_creation toggles whether MsgCreateSpotMarket can
	// be executed by non-gov authority. Phase 1 = true.
	GovOnlyMarketCreation bool `protobuf:"varint,2,opt,name=gov_only_market_creation,json=govOnlyMarketCreation,proto3" json:"gov_only_market_creation,omitempty"`
	// fill_retention_blocks is how many blocks of SpotFill history we
	// retain per market. 0 = keep all (unbounded).
	FillRetentionBlocks uint32 `protobuf:"varint,3,opt,name=fill_retention_blocks,json=fillRetentionBlocks,proto3" json:"fill_retention_blocks,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_5543a6e189c441d2, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMaxOpenOrdersPerAccount() uint32 {
	if m != nil {
		return m.MaxOpenOrdersPerAccount
	}
	return 0
}

func (m *Params) GetGovOnlyMarketCreation() bool {
	if m != nil {
		return m.GovOnlyMarketCreation
	}
	return false
}

func (m *Params) GetFillRetentionBlocks() uint32 {
	if m != nil {
		return m.FillRetentionBlocks
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "ltrstchain.ltrstdex.Params")
}

func init() { proto.RegisterFile("ltrstchain/ltrstdex/params.proto", fileDescriptor_5543a6e189c441d2) }

var fileDescriptor_5543a6e189c441d2 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc8, 0x29, 0x29, 0x2a,
	0x2e, 0x49, 0xce, 0x48, 0xcc, 0xcc, 0xd3, 0x07, 0x33, 0x53, 0x52, 0x2b, 0xf4, 0x0b, 0x12, 0x8b,
	0x12, 0x73, 0x8b, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x84, 0x11, 0x2a, 0xf4, 0x60, 0x2a,
	0xa4, 0x04, 0x13, 0x73, 0x33, 0xf3, 0xf2, 0xf5, 0xc1, 0x24, 0x44, 0x9d, 0x94, 0x48, 0x7a, 0x7e,
	0x7a, 0x3e, 0x98, 0xa9, 0x0f, 0x62, 0x41, 0x44, 0x95, 0x6e, 0x31, 0x72, 0xb1, 0x05, 0x80, 0x8d,
	0x13, 0xb2, 0xe1, 0x92, 0xce, 0x4d, 0xac, 0x88, 0xcf, 0x2f, 0x48, 0xcd, 0x8b, 0xcf, 0x2f, 0x4a,
	0x49, 0x2d, 0x2a, 0x8e, 0x2f, 0x48, 0x2d, 0x8a, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x91,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d, 0x12, 0xcf, 0x4d, 0xac, 0xf0, 0x2f, 0x48, 0xcd, 0xf3, 0x07,
	0x2b, 0x08, 0x48, 0x2d, 0x72, 0x84, 0x48, 0x0b, 0x99, 0x73, 0x49, 0xa4, 0xe7, 0x97, 0xc5, 0xe7,
	0xe7, 0xe5, 0x54, 0xc6, 0xe7, 0x26, 0x16, 0x65, 0xa7, 0x96, 0xc4, 0x27, 0x17, 0xa5, 0x26, 0x96,
	0x64, 0xe6, 0xe7, 0x49, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x04, 0x89, 0xa6, 0xe7, 0x97, 0xf9, 0xe7,
	0xe5, 0x54, 0xfa, 0x82, 0x65, 0x9d, 0xa1, 0x92, 0x42, 0x46, 0x5c, 0xa2, 0x69, 0x99, 0x39, 0x39,
	0xf1, 0x45, 0xa9, 0x25, 0xa9, 0x79, 0x20, 0x91, 0xf8, 0xa4, 0x9c, 0xfc, 0xe4, 0xec, 0x62, 0x09,
	0x66, 0xb0, 0x85, 0xc2, 0x20, 0xc9, 0x20, 0x98, 0x9c, 0x13, 0x58, 0xca, 0x4a, 0xf5, 0xc5, 0x02,
	0x79, 0xc6, 0xae, 0xe7, 0x1b, 0xb4, 0x64, 0x90, 0x82, 0xa7, 0x02, 0x11, 0x40, 0x10, 0x1f, 0x39,
	0x99, 0x9e, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13, 0x1e,
	0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x34, 0x76, 0x7d, 0x25,
	0x95, 0x05, 0xa9, 0xc5, 0x49, 0x6c, 0xe0, 0xa0, 0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0xf2, 0xbe, 0xd9, 0x7c, 0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.MaxOpenOrdersPerAccount != that1.MaxOpenOrdersPerAccount {
		return false
	}
	if this.GovOnlyMarketCreation != that1.GovOnlyMarketCreation {
		return false
	}
	if this.FillRetentionBlocks != that1.FillRetentionBlocks {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FillRetentionBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.FillRetentionBlocks))
		i--
		dAtA[i] = 0x18
	}
	if m.GovOnlyMarketCreation {
		i--
		if m.GovOnlyMarketCreation {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.MaxOpenOrdersPerAccount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxOpenOrdersPerAccount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MaxOpenOrdersPerAccount != 0 {
		n += 1 + sovParams(uint64(m.MaxOpenOrdersPerAccount))
	}
	if m.GovOnlyMarketCreation {
		n += 2
	}
	if m.FillRetentionBlocks != 0 {
		n += 1 + sovParams(uint64(m.FillRetentionBlocks))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxOpenOrdersPerAccount", wireType)
			}
			m.MaxOpenOrdersPerAccount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxOpenOrdersPerAccount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GovOnlyMarketCreation", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.GovOnlyMarketCreation = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FillRetentionBlocks", wireType)
			}
			m.FillRetentionBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FillRetentionBlocks |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
