// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ltrstchain/ltrstdex/spot.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Side is whether an order buys or sells the base asset of a market.
type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_SIDE_BUY         Side = 1
	Side_SIDE_SELL        Side = 2
)

var Side_name = map[int32]string{
	0: "SIDE_UNSPECIFIED",
	1: "SIDE_BUY",
	2: "SIDE_SELL",
}

var Side_value = map[string]int32{
	"SIDE_UNSPECIFIED": 0,
	"SIDE_BUY":         1,
	"SIDE_SELL":        2,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}

func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c01d9e2c7eb3d746, []int{0}
}

// OrderType controls whether an order needs a limit price.
type OrderType int32

const (
	OrderType_ORDER_TYPE_UNSPECIFIED OrderType = 0
	OrderType_ORDER_TYPE_LIMIT       OrderType = 1
	OrderType_ORDER_TYPE_MARKET      OrderType = 2
)

var OrderType_name = map[int32]string{
	0: "ORDER_TYPE_UNSPECIFIED",
	1: "ORDER_TYPE_LIMIT",
	2: "ORDER_TYPE_MARKET",
}

var OrderType_value = map[string]int32{
	"ORDER_TYPE_UNSPECIFIED": 0,
	"ORDER_TYPE_LIMIT":       1,
	"ORDER_TYPE_MARKET":      2,
}

func (x OrderType) String() string {
	return proto.EnumName(OrderType_name, int32(x))
}

func (OrderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c01d9e2c7eb3d746, []int{1}
}

// TimeInForce controls how remaining quantity behaves after match.
type TimeInForce int32

const (
	// Good till cancelled. Any unfilled remainder rests on the book
	// until owner cancels or expires_at_block is reached.
	TimeInForce_TIF_GTC TimeInForce = 0
	// Immediate or cancel. Unfilled remainder refunded and not posted.
	TimeInForce_TIF_IOC TimeInForce = 1
	// Fill or kill. If entire quantity can't be filled at placement,
	// reject atomically with no state change.
	TimeInForce_TIF_FOK TimeInForce = 2
)

var TimeInForce_name = map[int32]string{
	0: "TIF_GTC",
	1: "TIF_IOC",
	2: "TIF_FOK",
}

var TimeInForce_value = map[string]int32{
	"TIF_GTC": 0,
	"TIF_IOC": 1,
	"TIF_FOK": 2,
}

func (x TimeInForce) String() string {
	return proto.EnumName(TimeInForce_name, int32(x))
}

func (TimeInForce) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c01d9e2c7eb3d746, []int{2}
}

// MarketStatus gates which operations are valid against a market.
type MarketStatus int32

const (
	MarketStatus_MARKET_STATUS_UNSPECIFIED MarketStatus = 0
	// PRE_OPEN: market exists, order placement rejected.
	MarketStatus_MARKET_STATUS_PRE_OPEN MarketStatus = 1
	// ACTIVE: normal trading.
	MarketStatus_MARKET_STATUS_ACTIVE MarketStatus = 2
	// POST_ONLY: only maker orders accepted (no taker / crossing).
	MarketStatus_MARKET_STATUS_POST_ONLY MarketStatus = 3
	// PAUSED: no new orders, existing orders remain on book.
	MarketStatus_MARKET_STATUS_PAUSED MarketStatus = 4
	// HALTED: no new orders; existing orders auto-cancelled next block.
	MarketStatus_MARKET_STATUS_HALTED MarketStatus = 5
)

var MarketStatus_name = map[int32]string{
	0: "MARKET_STATUS_UNSPECIFIED",
	1: "MARKET_STATUS_PRE_OPEN",
	2: "MARKET_STATUS_ACTIVE",
	3: "MARKET_STATUS_POST_ONLY",
	4: "MARKET_STATUS_PAUSED",
	5: "MARKET_STATUS_HALTED",
}

var MarketStatus_value = map[string]int32{
	"MARKET_STATUS_UNSPECIFIED": 0,
	"MARKET_STATUS_PRE_OPEN":    1,
	"MARKET_STATUS_ACTIVE":      2,
	"MARKET_STATUS_POST_ONLY":   3,
	"MARKET_STATUS_PAUSED":      4,
	"MARKET_STATUS_HALTED":      5,
}

func (x MarketStatus) String() string {
	return proto.EnumName(MarketStatus_name, int32(x))
}

func (MarketStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c01d9e2c7eb3d746, []int{3}
}

// SpotMarket is a tradeable base/quote pair.
type SpotMarket struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// ticker is the human-readable display, e.g. "LTRST/USDC".
	Ticker string `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	// base_denom is the denom that an order quantity is denominated in.
	BaseDenom string `protobuf:"bytes,3,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty"`
	// quote_denom is the denom used for price and for collateral locked
	// by BUY orders.
	QuoteDenom string `protobuf:"bytes,4,opt,name=quote_denom,json=quoteDenom,proto3" json:"quote_denom,omitempty"`
	// min_price_tick is the minimum increment of price. LegacyDec.
	MinPriceTick cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=min_price_tick,json=minPriceTick,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_price_tick"`
	// min_quantity is the minimum order size (in base units). LegacyDec.
	MinQuantity cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=min_quantity,json=minQuantity,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_quantity"`
	// maker_fee_bps is basis points (1/10000) taken from maker.
	// Phase 1 = 0.
	MakerFeeBps uint32 `protobuf:"varint,7,opt,name=maker_fee_bps,json=makerFeeBps,proto3" json:"maker_fee_bps,omitempty"`
	// taker_fee_bps is basis points (1/10000) taken from taker.
	TakerFeeBps uint32       `protobuf:"varint,8,opt,name=taker_fee_bps,json=takerFeeBps,proto3" json:"taker_fee_bps,omitempty"`
	Status      MarketStatus `protobuf:"varint,9,opt,name=status,proto3,enum=ltrstchain.ltrstdex.MarketStatus" json:"status,omitempty"`
	// created_at_block is the height at which gov created the market.
	CreatedAtBlock int64 `protobuf:"varint,10,opt,name=created_at_block,json=createdAtBlock,proto3" json:"created_at_block,omitempty"`
}

func (m *SpotMarket) Reset()         { *m = SpotMarket{} }
func (m *SpotMarket) String() string { return proto.CompactTextString(m) }
func (*SpotMarket) ProtoMessage()    {}
func (*SpotMarket) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01d9e2c7eb3d746, []int{0}
}
func (m *SpotMarket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpotMarket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpotMarket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpotMarket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotMarket.Merge(m, src)
}
func (m *SpotMarket) XXX_Size() int {
	return m.Size()
}
func (m *SpotMarket) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotMarket.DiscardUnknown(m)
}

var xxx_messageInfo_SpotMarket proto.InternalMessageInfo

func (m *SpotMarket) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SpotMarket) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *SpotMarket) GetBaseDenom() string {
	if m != nil {
		return m.BaseDenom
	}
	return ""
}

func (m *SpotMarket) GetQuoteDenom() string {
	if m != nil {
		return m.QuoteDenom
	}
	return ""
}

func (m *SpotMarket) GetMakerFeeBps() uint32 {
	if m != nil {
		return m.MakerFeeBps
	}
	return 0
}

func (m *SpotMarket) GetTakerFeeBps() uint32 {
	if m != nil {
		return m.TakerFeeBps
	}
	return 0
}

func (m *SpotMarket) GetStatus() MarketStatus {
	if m != nil {
		return m.Status
	}
	return MarketStatus_MARKET_STATUS_UNSPECIFIED
}

func (m *SpotMarket) GetCreatedAtBlock() int64 {
	if m != nil {
		return m.CreatedAtBlock
	}
	return 0
}

// SpotOrder is a live or historical order record.
type SpotOrder struct {
	// order_id is a deterministic hex string — hash(owner || market || seq).
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// owner is the sdk.AccAddress bytes of the order placer.
	Owner    []byte      `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	MarketId uint64      `protobuf:"varint,3,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side     Side        `protobuf:"varint,4,opt,name=side,proto3,enum=ltrstchain.ltrstdex.Side" json:"side,omitempty"`
	Type     OrderType   `protobuf:"varint,5,opt,name=type,proto3,enum=ltrstchain.ltrstdex.OrderType" json:"type,omitempty"`
	Tif      TimeInForce `protobuf:"varint,6,opt,name=tif,proto3,enum=ltrstchain.ltrstdex.TimeInForce" json:"tif,omitempty"`
	// price is a LegacyDec, quote units per base unit. Empty/"0" is
	// only allowed for ORDER_TYPE_MARKET.
	Price cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	// quantity is the total base-asset quantity of the order.
	Quantity cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=quantity,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"quantity"`
	// filled_quantity is cumulative base-asset filled so far.
	FilledQuantity cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=filled_quantity,json=filledQuantity,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"filled_quantity"`
	// locked_amount is the amount still escrowed for this order.
	// For BUY orders: denominated in quote_denom.
	// For SELL orders: denominated in base_denom.
	LockedAmount  cosmossdk_io_math.LegacyDec `protobuf:"bytes,10,opt,name=locked_amount,json=lockedAmount,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"locked_amount"`
	CreatedHeight int64                       `protobuf:"varint,11,opt,name=created_height,json=createdHeight,proto3" json:"created_height,omitempty"`
	// seq is a monotonic per-market placement sequence number, used as
	// the time-priority tie-breaker inside a price level.
	Seq uint64 `protobuf:"varint,12,opt,name=seq,proto3" json:"seq,omitempty"`
	// expires_at_block is the height after which the order auto-cancels.
	// 0 = never expire (until manually cancelled).
	ExpiresAtBlock int64 `protobuf:"varint,13,opt,name=expires_at_block,json=expiresAtBlock,proto3" json:"expires_at_block,omitempty"`
}

func (m *SpotOrder) Reset()         { *m = SpotOrder{} }
func (m *SpotOrder) String() string { return proto.CompactTextString(m) }
func (*SpotOrder) ProtoMessage()    {}
func (*SpotOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01d9e2c7eb3d746, []int{1}
}
func (m *SpotOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpotOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpotOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpotOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotOrder.Merge(m, src)
}
func (m *SpotOrder) XXX_Size() int {
	return m.Size()
}
func (m *SpotOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SpotOrder proto.InternalMessageInfo

func (m *SpotOrder) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *SpotOrder) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *SpotOrder) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *SpotOrder) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *SpotOrder) GetType() OrderType {
	if m != nil {
		return m.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *SpotOrder) GetTif() TimeInForce {
	if m != nil {
		return m.Tif
	}
	return TimeInForce_TIF_GTC
}

func (m *SpotOrder) GetCreatedHeight() int64 {
	if m != nil {
		return m.CreatedHeight
	}
	return 0
}

func (m *SpotOrder) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SpotOrder) GetExpiresAtBlock() int64 {
	if m != nil {
		return m.ExpiresAtBlock
	}
	return 0
}

// SpotFill records a single match between a taker and a maker.
type SpotFill struct {
	FillSeq      uint64 `protobuf:"varint,1,opt,name=fill_seq,json=fillSeq,proto3" json:"fill_seq,omitempty"`
	MarketId     uint64 `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	TakerOrderId string `protobuf:"bytes,3,opt,name=taker_order_id,json=takerOrderId,proto3" json:"taker_order_id,omitempty"`
	MakerOrderId string `protobuf:"bytes,4,opt,name=maker_order_id,json=makerOrderId,proto3" json:"maker_order_id,omitempty"`
	Taker        []byte `protobuf:"bytes,5,opt,name=taker,proto3" json:"taker,omitempty"`
	Maker        []byte `protobuf:"bytes,6,opt,name=maker,proto3" json:"maker,omitempty"`
	// taker_side is the side the taker was on (BUY or SELL).
	TakerSide Side `protobuf:"varint,7,opt,name=taker_side,json=takerSide,proto3,enum=ltrstchain.ltrstdex.Side" json:"taker_side,omitempty"`
	// price is the execution price (the maker's resting price).
	Price cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	// quantity is base-units filled in this match.
	Quantity cosmossdk_io_math.LegacyDec `protobuf:"bytes,9,opt,name=quantity,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"quantity"`
	// taker_fee is quote-denom fee paid by the taker to fee_collector.
	TakerFee cosmossdk_io_math.LegacyDec `protobuf:"bytes,10,opt,name=taker_fee,json=takerFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"taker_fee"`
	// maker_fee is quote-denom fee paid by the maker. 0 in Phase 1.
	MakerFee    cosmossdk_io_math.LegacyDec `protobuf:"bytes,11,opt,name=maker_fee,json=makerFee,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"maker_fee"`
	BlockHeight int64                       `protobuf:"varint,12,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *SpotFill) Reset()         { *m = SpotFill{} }
func (m *SpotFill) String() string { return proto.CompactTextString(m) }
func (*SpotFill) ProtoMessage()    {}
func (*SpotFill) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01d9e2c7eb3d746, []int{2}
}
func (m *SpotFill) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SpotFill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SpotFill.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SpotFill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpotFill.Merge(m, src)
}
func (m *SpotFill) XXX_Size() int {
	return m.Size()
}
func (m *SpotFill) XXX_DiscardUnknown() {
	xxx_messageInfo_SpotFill.DiscardUnknown(m)
}

var xxx_messageInfo_SpotFill proto.InternalMessageInfo

func (m *SpotFill) GetFillSeq() uint64 {
	if m != nil {
		return m.FillSeq
	}
	return 0
}

func (m *SpotFill) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *SpotFill) GetTakerOrderId() string {
	if m != nil {
		return m.TakerOrderId
	}
	return ""
}

func (m *SpotFill) GetMakerOrderId() string {
	if m != nil {
		return m.MakerOrderId
	}
	return ""
}

func (m *SpotFill) GetTaker() []byte {
	if m != nil {
		return m.Taker
	}
	return nil
}

func (m *SpotFill) GetMaker() []byte {
	if m != nil {
		return m.Maker
	}
	return nil
}

func (m *SpotFill) GetTakerSide() Side {
	if m != nil {
		return m.TakerSide
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *SpotFill) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

// OrderbookLevel is an aggregated depth level for query responses.
type OrderbookLevel struct {
	Price         cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	TotalQuantity cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=total_quantity,json=totalQuantity,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"total_quantity"`
	OrderCount    uint32                      `protobuf:"varint,3,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
}

func (m *OrderbookLevel) Reset()         { *m = OrderbookLevel{} }
func (m *OrderbookLevel) String() string { return proto.CompactTextString(m) }
func (*OrderbookLevel) ProtoMessage()    {}
func (*OrderbookLevel) Descriptor() ([]byte, []int) {
	return fileDescriptor_c01d9e2c7eb3d746, []int{3}
}
func (m *OrderbookLevel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrderbookLevel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrderbookLevel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrderbookLevel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderbookLevel.Merge(m, src)
}
func (m *OrderbookLevel) XXX_Size() int {
	return m.Size()
}
func (m *OrderbookLevel) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderbookLevel.DiscardUnknown(m)
}

var xxx_messageInfo_OrderbookLevel proto.InternalMessageInfo

func (m *OrderbookLevel) GetOrderCount() uint32 {
	if m != nil {
		return m.OrderCount
	}
	return 0
}

func init() {
	proto.RegisterEnum("ltrstchain.ltrstdex.Side", Side_name, Side_value)
	proto.RegisterEnum("ltrstchain.ltrstdex.OrderType", OrderType_name, OrderType_value)
	proto.RegisterEnum("ltrstchain.ltrstdex.TimeInForce", TimeInForce_name, TimeInForce_value)
	proto.RegisterEnum("ltrstchain.ltrstdex.MarketStatus", MarketStatus_name, MarketStatus_value)
	proto.RegisterType((*SpotMarket)(nil), "ltrstchain.ltrstdex.SpotMarket")
	proto.RegisterType((*SpotOrder)(nil), "ltrstchain.ltrstdex.SpotOrder")
	proto.RegisterType((*SpotFill)(nil), "ltrstchain.ltrstdex.SpotFill")
	proto.RegisterType((*OrderbookLevel)(nil), "ltrstchain.ltrstdex.OrderbookLevel")
}

func init() { proto.RegisterFile("ltrstchain/ltrstdex/spot.proto", fileDescriptor_c01d9e2c7eb3d746) }

var fileDescriptor_c01d9e2c7eb3d746 = []byte{
	// 1027 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x96, 0xcd, 0x6e, 0xe3, 0x54,
	0x14, 0xc7, 0xe3, 0x24, 0x6d, 0xe3, 0x13, 0xc7, 0x78, 0x2e, 0xa1, 0xb8, 0xad, 0x26, 0xcd, 0x94,
	0x41, 0x8a, 0x2a, 0x91, 0x4a, 0x01, 0x24, 0xca, 0x06, 0xd2, 0xc6, 0xa1, 0x66, 0xd2, 0x26, 0xd8,
	0x2e, 0x52, 0xd9, 0x58, 0xae, 0x7d, 0xdb, 0x5a, 0x89, 0xe3, 0xd4, 0xbe, 0x85, 0xf6, 0x2d, 0x78,
	0x01, 0x24, 0x1e, 0x82, 0x05, 0xe2, 0x09, 0x66, 0x39, 0x4b, 0xc4, 0x62, 0x84, 0xda, 0x0d, 0x1b,
	0xde, 0x01, 0xdd, 0x73, 0xf3, 0xd5, 0x4e, 0x25, 0x32, 0xb0, 0xa9, 0xee, 0xf9, 0x9f, 0x8f, 0x26,
	0xfe, 0xff, 0xee, 0x89, 0xa1, 0x32, 0x60, 0x49, 0xca, 0xfc, 0x0b, 0x2f, 0x1c, 0xee, 0xe0, 0x31,
	0xa0, 0xd7, 0x3b, 0xe9, 0x28, 0x66, 0xf5, 0x51, 0x12, 0xb3, 0x98, 0xbc, 0x3b, 0xcb, 0xd7, 0x27,
	0xf9, 0xf5, 0x27, 0x5e, 0x14, 0x0e, 0xe3, 0x1d, 0xfc, 0x2b, 0xea, 0xd6, 0xcb, 0xe7, 0xf1, 0x79,
	0x8c, 0xc7, 0x1d, 0x7e, 0x12, 0xea, 0xd6, 0x6f, 0x39, 0x00, 0x7b, 0x14, 0xb3, 0x43, 0x2f, 0xe9,
	0x53, 0x46, 0x54, 0xc8, 0x86, 0x81, 0x2e, 0x55, 0xa5, 0x5a, 0xde, 0xca, 0x86, 0x01, 0x59, 0x85,
	0x65, 0x16, 0xfa, 0x7d, 0x9a, 0xe8, 0xd9, 0xaa, 0x54, 0x93, 0xad, 0x71, 0x44, 0x9e, 0x02, 0x9c,
	0x7a, 0x29, 0x75, 0x03, 0x3a, 0x8c, 0x23, 0x3d, 0x87, 0x39, 0x99, 0x2b, 0x2d, 0x2e, 0x90, 0x4d,
	0x28, 0x5e, 0x5e, 0xc5, 0x6c, 0x92, 0xcf, 0x63, 0x1e, 0x50, 0x12, 0x05, 0x26, 0xa8, 0x51, 0x38,
	0x74, 0x47, 0x49, 0xe8, 0x53, 0x97, 0xcf, 0xd4, 0x97, 0x78, 0xcd, 0xde, 0x07, 0x2f, 0x5f, 0x6f,
	0x66, 0xfe, 0x78, 0xbd, 0xb9, 0xe1, 0xc7, 0x69, 0x14, 0xa7, 0x69, 0xd0, 0xaf, 0x87, 0xf1, 0x4e,
	0xe4, 0xb1, 0x8b, 0x7a, 0x87, 0x9e, 0x7b, 0xfe, 0x4d, 0x8b, 0xfa, 0x96, 0x12, 0x85, 0xc3, 0x1e,
	0xef, 0x74, 0x42, 0xbf, 0x4f, 0xda, 0xc0, 0x63, 0xf7, 0xf2, 0xca, 0x1b, 0xb2, 0x90, 0xdd, 0xe8,
	0xcb, 0x8b, 0x0f, 0x2a, 0x46, 0xe1, 0xf0, 0x9b, 0x71, 0x1f, 0xd9, 0x82, 0x52, 0xe4, 0xf5, 0x69,
	0xe2, 0x9e, 0x51, 0xea, 0x9e, 0x8e, 0x52, 0x7d, 0xa5, 0x2a, 0xd5, 0x4a, 0x56, 0x11, 0xc5, 0x36,
	0xa5, 0x7b, 0xa3, 0x94, 0xd7, 0xb0, 0x7b, 0x35, 0x05, 0x51, 0xc3, 0xe6, 0x6a, 0x76, 0x61, 0x39,
	0x65, 0x1e, 0xbb, 0x4a, 0x75, 0xb9, 0x2a, 0xd5, 0xd4, 0xc6, 0xb3, 0xfa, 0x23, 0x06, 0xd5, 0xc5,
	0xf3, 0xb6, 0xb1, 0xd0, 0x1a, 0x37, 0x90, 0x1a, 0x68, 0x7e, 0x42, 0x3d, 0x46, 0x03, 0xd7, 0x63,
	0xee, 0xe9, 0x20, 0xf6, 0xfb, 0x3a, 0x54, 0xa5, 0x5a, 0xce, 0x52, 0xc7, 0x7a, 0x93, 0xed, 0x71,
	0xf5, 0xf3, 0xfc, 0x5f, 0x3f, 0x6f, 0x4a, 0x5b, 0x7f, 0xe7, 0x41, 0xe6, 0xe6, 0x75, 0x93, 0x80,
	0x26, 0x64, 0x0d, 0x0a, 0x31, 0x3f, 0xb8, 0x63, 0x07, 0x65, 0x6b, 0x05, 0x63, 0x33, 0x20, 0x65,
	0x58, 0x8a, 0x7f, 0x18, 0x8e, 0x5d, 0x54, 0x2c, 0x11, 0x90, 0x0d, 0x90, 0x23, 0xfc, 0x18, 0xbc,
	0x23, 0x87, 0x9e, 0x17, 0x84, 0x60, 0x06, 0xe4, 0x23, 0xc8, 0xa7, 0x61, 0x40, 0xd1, 0x3b, 0xb5,
	0xb1, 0xf6, 0xe8, 0x97, 0xb0, 0xc3, 0x80, 0x5a, 0x58, 0x46, 0x1a, 0x90, 0x67, 0x37, 0x23, 0x8a,
	0x36, 0xaa, 0x8d, 0xca, 0xa3, 0xe5, 0xf8, 0x31, 0x9d, 0x9b, 0x11, 0xb5, 0xb0, 0x96, 0x34, 0x20,
	0xc7, 0xc2, 0x33, 0x34, 0x4c, 0x6d, 0x54, 0x1f, 0x6d, 0x71, 0xc2, 0x88, 0x9a, 0xc3, 0x76, 0x9c,
	0xf8, 0xd4, 0xe2, 0xc5, 0x64, 0x17, 0x96, 0x10, 0x1a, 0x74, 0x67, 0x41, 0x9b, 0x45, 0x07, 0xf9,
	0x02, 0x0a, 0x53, 0x48, 0x0a, 0x8b, 0x77, 0x4f, 0x9b, 0x48, 0x07, 0xde, 0x39, 0x0b, 0x07, 0x03,
	0x1a, 0xcc, 0x60, 0x93, 0x17, 0x9f, 0xa3, 0x8a, 0xde, 0x29, 0x6f, 0x07, 0x50, 0xe2, 0x56, 0x72,
	0xaf, 0xa3, 0xf8, 0x6a, 0xc8, 0xd0, 0xe9, 0x45, 0x6f, 0x80, 0xe8, 0x6c, 0x62, 0x23, 0xf9, 0x10,
	0x26, 0x78, 0xb8, 0x17, 0x34, 0x3c, 0xbf, 0x60, 0x7a, 0x11, 0xa1, 0x29, 0x8d, 0xd5, 0x03, 0x14,
	0x89, 0x06, 0xb9, 0x94, 0x5e, 0xea, 0x0a, 0x1a, 0xcd, 0x8f, 0x9c, 0x37, 0x7a, 0x3d, 0x0a, 0x13,
	0x9a, 0xce, 0x78, 0x2b, 0x09, 0xde, 0xc6, 0xfa, 0x3c, 0x6f, 0x99, 0xad, 0x9f, 0xf2, 0x50, 0xe0,
	0xbc, 0xb5, 0xc3, 0xc1, 0x80, 0xe3, 0xc6, 0xbf, 0x91, 0xcb, 0x67, 0x8a, 0x85, 0xb1, 0xc2, 0x63,
	0x9b, 0x5e, 0xde, 0x07, 0x2b, 0xfb, 0x00, 0xac, 0xe7, 0xa0, 0x8a, 0x3b, 0x34, 0x85, 0x55, 0xac,
	0x0f, 0x05, 0xd5, 0xee, 0x98, 0xd8, 0xe7, 0xa0, 0x46, 0xf7, 0xab, 0xc4, 0x12, 0x51, 0xa2, 0xf9,
	0xaa, 0x32, 0x2c, 0x61, 0x17, 0x62, 0xa7, 0x58, 0x22, 0xe0, 0x2a, 0x56, 0x21, 0x59, 0x8a, 0x25,
	0x02, 0xf2, 0x19, 0x80, 0xf8, 0xbf, 0x88, 0xf5, 0xca, 0xbf, 0x61, 0x2d, 0x63, 0x31, 0x3f, 0xce,
	0x98, 0x2b, 0xfc, 0x2f, 0xe6, 0xe4, 0xff, 0xc2, 0xdc, 0x97, 0x20, 0x4f, 0x37, 0xce, 0xdb, 0x10,
	0x52, 0x98, 0xac, 0x24, 0x3e, 0x61, 0xba, 0xd7, 0x10, 0x8c, 0x45, 0x27, 0x4c, 0x16, 0x1f, 0x79,
	0x06, 0x0a, 0xb2, 0x31, 0xa1, 0x4b, 0x41, 0x44, 0x8a, 0xa8, 0x09, 0xb6, 0xc6, 0x7c, 0xfc, 0x2a,
	0x81, 0x8a, 0xd6, 0x9c, 0xc6, 0x71, 0xbf, 0x43, 0xbf, 0xa7, 0x83, 0xd9, 0xb3, 0x93, 0xde, 0xfa,
	0xd9, 0x7d, 0x0d, 0x2a, 0x8b, 0x99, 0x37, 0x98, 0xdd, 0xb6, 0xec, 0xe2, 0x33, 0x4a, 0xd8, 0x3a,
	0xbd, 0x6c, 0x9b, 0x50, 0x14, 0x20, 0xf9, 0x78, 0xd5, 0x72, 0xb8, 0xb6, 0x01, 0xa5, 0x7d, 0xae,
	0x6c, 0xef, 0x42, 0x1e, 0xbd, 0x2e, 0x83, 0x66, 0x9b, 0x2d, 0xc3, 0x3d, 0x3e, 0xb2, 0x7b, 0xc6,
	0xbe, 0xd9, 0x36, 0x8d, 0x96, 0x96, 0x21, 0x0a, 0x14, 0x50, 0xdd, 0x3b, 0x3e, 0xd1, 0x24, 0x52,
	0x02, 0x19, 0x23, 0xdb, 0xe8, 0x74, 0xb4, 0xec, 0xb6, 0x03, 0xf2, 0x74, 0xb3, 0x91, 0x75, 0x58,
	0xed, 0x5a, 0x2d, 0xc3, 0x72, 0x9d, 0x93, 0xde, 0xc3, 0x29, 0x65, 0xd0, 0xe6, 0x72, 0x1d, 0xf3,
	0xd0, 0x74, 0x34, 0x89, 0xbc, 0x07, 0x4f, 0xe6, 0xd4, 0xc3, 0xa6, 0xf5, 0xc2, 0x70, 0xb4, 0xec,
	0xf6, 0x27, 0x50, 0x9c, 0x5b, 0x7e, 0xa4, 0x08, 0x2b, 0x8e, 0xd9, 0x76, 0xbf, 0x72, 0xf6, 0xb5,
	0xcc, 0x24, 0x30, 0xbb, 0xfb, 0x9a, 0x34, 0x09, 0xda, 0xdd, 0x17, 0x5a, 0x76, 0xfb, 0x17, 0x09,
	0x94, 0xf9, 0x9f, 0x16, 0xf2, 0x14, 0xd6, 0xc4, 0x48, 0xd7, 0x76, 0x9a, 0xce, 0xb1, 0xfd, 0xe0,
	0x23, 0xad, 0xc3, 0xea, 0xfd, 0x74, 0xcf, 0x32, 0xdc, 0x6e, 0xcf, 0x38, 0xd2, 0x24, 0xa2, 0x43,
	0xf9, 0x7e, 0xae, 0xb9, 0xef, 0x98, 0xdf, 0x1a, 0x5a, 0x96, 0x6c, 0xc0, 0xfb, 0x0f, 0xba, 0xba,
	0xb6, 0xe3, 0x76, 0x8f, 0x3a, 0x27, 0x5a, 0xee, 0xcd, 0xb6, 0x5e, 0xf3, 0xd8, 0x36, 0x5a, 0x5a,
	0xfe, 0xcd, 0xcc, 0x41, 0xb3, 0xe3, 0x18, 0x2d, 0x6d, 0x69, 0xef, 0xd3, 0x97, 0xb7, 0x15, 0xe9,
	0xd5, 0x6d, 0x45, 0xfa, 0xf3, 0xb6, 0x22, 0xfd, 0x78, 0x57, 0xc9, 0xbc, 0xba, 0xab, 0x64, 0x7e,
	0xbf, 0xab, 0x64, 0xbe, 0xdb, 0x98, 0x7b, 0xfb, 0xb9, 0x9e, 0xbd, 0xff, 0xf0, 0xdf, 0x8f, 0xf4,
	0x74, 0x19, 0xdf, 0x61, 0x3e, 0xfe, 0x27, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x0e, 0xf9, 0xe7, 0x23,
	0x09, 0x00, 0x00,
}

func (this *SpotMarket) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SpotMarket)
	if !ok {
		that2, ok := that.(SpotMarket)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.Ticker != that1.Ticker {
		return false
	}
	if this.BaseDenom != that1.BaseDenom {
		return false
	}
	if this.QuoteDenom != that1.QuoteDenom {
		return false
	}
	if !this.MinPriceTick.Equal(that1.MinPriceTick) {
		return false
	}
	if !this.MinQuantity.Equal(that1.MinQuantity) {
		return false
	}
	if this.MakerFeeBps != that1.MakerFeeBps {
		return false
	}
	if this.TakerFeeBps != that1.TakerFeeBps {
		return false
	}
	if this.Status != that1.Status {
		return false
	}
	if this.CreatedAtBlock != that1.CreatedAtBlock {
		return false
	}
	return true
}
func (m *SpotMarket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpotMarket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpotMarket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAtBlock != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.CreatedAtBlock))
		i--
		dAtA[i] = 0x50
	}
	if m.Status != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x48
	}
	if m.TakerFeeBps != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.TakerFeeBps))
		i--
		dAtA[i] = 0x40
	}
	if m.MakerFeeBps != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.MakerFeeBps))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.MinQuantity.Size()
		i -= size
		if _, err := m.MinQuantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MinPriceTick.Size()
		i -= size
		if _, err := m.MinPriceTick.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.QuoteDenom) > 0 {
		i -= len(m.QuoteDenom)
		copy(dAtA[i:], m.QuoteDenom)
		i = encodeVarintSpot(dAtA, i, uint64(len(m.QuoteDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BaseDenom) > 0 {
		i -= len(m.BaseDenom)
		copy(dAtA[i:], m.BaseDenom)
		i = encodeVarintSpot(dAtA, i, uint64(len(m.BaseDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Ticker) > 0 {
		i -= len(m.Ticker)
		copy(dAtA[i:], m.Ticker)
		i = encodeVarintSpot(dAtA, i, uint64(len(m.Ticker)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SpotOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpotOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpotOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ExpiresAtBlock != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.ExpiresAtBlock))
		i--
		dAtA[i] = 0x68
	}
	if m.Seq != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.Seq))
		i--
		dAtA[i] = 0x60
	}
	if m.CreatedHeight != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.CreatedHeight))
		i--
		dAtA[i] = 0x58
	}
	{
		size := m.LockedAmount.Size()
		i -= size
		if _, err := m.LockedAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.FilledQuantity.Size()
		i -= size
		if _, err := m.FilledQuantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.Quantity.Size()
		i -= size
		if _, err := m.Quantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.Tif != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.Tif))
		i--
		dAtA[i] = 0x30
	}
	if m.Type != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x28
	}
	if m.Side != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.Side))
		i--
		dAtA[i] = 0x20
	}
	if m.MarketId != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintSpot(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrderId) > 0 {
		i -= len(m.OrderId)
		copy(dAtA[i:], m.OrderId)
		i = encodeVarintSpot(dAtA, i, uint64(len(m.OrderId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SpotFill) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SpotFill) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SpotFill) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x60
	}
	{
		size := m.MakerFee.Size()
		i -= size
		if _, err := m.MakerFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	{
		size := m.TakerFee.Size()
		i -= size
		if _, err := m.TakerFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x52
	{
		size := m.Quantity.Size()
		i -= size
		if _, err := m.Quantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.TakerSide != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.TakerSide))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Maker) > 0 {
		i -= len(m.Maker)
		copy(dAtA[i:], m.Maker)
		i = encodeVarintSpot(dAtA, i, uint64(len(m.Maker)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Taker) > 0 {
		i -= len(m.Taker)
		copy(dAtA[i:], m.Taker)
		i = encodeVarintSpot(dAtA, i, uint64(len(m.Taker)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.MakerOrderId) > 0 {
		i -= len(m.MakerOrderId)
		copy(dAtA[i:], m.MakerOrderId)
		i = encodeVarintSpot(dAtA, i, uint64(len(m.MakerOrderId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TakerOrderId) > 0 {
		i -= len(m.TakerOrderId)
		copy(dAtA[i:], m.TakerOrderId)
		i = encodeVarintSpot(dAtA, i, uint64(len(m.TakerOrderId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MarketId != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x10
	}
	if m.FillSeq != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.FillSeq))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *OrderbookLevel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderbookLevel) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrderbookLevel) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.OrderCount != 0 {
		i = encodeVarintSpot(dAtA, i, uint64(m.OrderCount))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.TotalQuantity.Size()
		i -= size
		if _, err := m.TotalQuantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSpot(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintSpot(dAtA []byte, offset int, v uint64) int {
	offset -= sovSpot(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SpotMarket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovSpot(uint64(m.Id))
	}
	l = len(m.Ticker)
	if l > 0 {
		n += 1 + l + sovSpot(uint64(l))
	}
	l = len(m.BaseDenom)
	if l > 0 {
		n += 1 + l + sovSpot(uint64(l))
	}
	l = len(m.QuoteDenom)
	if l > 0 {
		n += 1 + l + sovSpot(uint64(l))
	}
	l = m.MinPriceTick.Size()
	n += 1 + l + sovSpot(uint64(l))
	l = m.MinQuantity.Size()
	n += 1 + l + sovSpot(uint64(l))
	if m.MakerFeeBps != 0 {
		n += 1 + sovSpot(uint64(m.MakerFeeBps))
	}
	if m.TakerFeeBps != 0 {
		n += 1 + sovSpot(uint64(m.TakerFeeBps))
	}
	if m.Status != 0 {
		n += 1 + sovSpot(uint64(m.Status))
	}
	if m.CreatedAtBlock != 0 {
		n += 1 + sovSpot(uint64(m.CreatedAtBlock))
	}
	return n
}

func (m *SpotOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovSpot(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovSpot(uint64(l))
	}
	if m.MarketId != 0 {
		n += 1 + sovSpot(uint64(m.MarketId))
	}
	if m.Side != 0 {
		n += 1 + sovSpot(uint64(m.Side))
	}
	if m.Type != 0 {
		n += 1 + sovSpot(uint64(m.Type))
	}
	if m.Tif != 0 {
		n += 1 + sovSpot(uint64(m.Tif))
	}
	l = m.Price.Size()
	n += 1 + l + sovSpot(uint64(l))
	l = m.Quantity.Size()
	n += 1 + l + sovSpot(uint64(l))
	l = m.FilledQuantity.Size()
	n += 1 + l + sovSpot(uint64(l))
	l = m.LockedAmount.Size()
	n += 1 + l + sovSpot(uint64(l))
	if m.CreatedHeight != 0 {
		n += 1 + sovSpot(uint64(m.CreatedHeight))
	}
	if m.Seq != 0 {
		n += 1 + sovSpot(uint64(m.Seq))
	}
	if m.ExpiresAtBlock != 0 {
		n += 1 + sovSpot(uint64(m.ExpiresAtBlock))
	}
	return n
}

func (m *SpotFill) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FillSeq != 0 {
		n += 1 + sovSpot(uint64(m.FillSeq))
	}
	if m.MarketId != 0 {
		n += 1 + sovSpot(uint64(m.MarketId))
	}
	l = len(m.TakerOrderId)
	if l > 0 {
		n += 1 + l + sovSpot(uint64(l))
	}
	l = len(m.MakerOrderId)
	if l > 0 {
		n += 1 + l + sovSpot(uint64(l))
	}
	l = len(m.Taker)
	if l > 0 {
		n += 1 + l + sovSpot(uint64(l))
	}
	l = len(m.Maker)
	if l > 0 {
		n += 1 + l + sovSpot(uint64(l))
	}
	if m.TakerSide != 0 {
		n += 1 + sovSpot(uint64(m.TakerSide))
	}
	l = m.Price.Size()
	n += 1 + l + sovSpot(uint64(l))
	l = m.Quantity.Size()
	n += 1 + l + sovSpot(uint64(l))
	l = m.TakerFee.Size()
	n += 1 + l + sovSpot(uint64(l))
	l = m.MakerFee.Size()
	n += 1 + l + sovSpot(uint64(l))
	if m.BlockHeight != 0 {
		n += 1 + sovSpot(uint64(m.BlockHeight))
	}
	return n
}

func (m *OrderbookLevel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Price.Size()
	n += 1 + l + sovSpot(uint64(l))
	l = m.TotalQuantity.Size()
	n += 1 + l + sovSpot(uint64(l))
	if m.OrderCount != 0 {
		n += 1 + sovSpot(uint64(m.OrderCount))
	}
	return n
}

func sovSpot(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSpot(x uint64) (n int) {
	return sovSpot(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SpotMarket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpotMarket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpotMarket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ticker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ticker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuoteDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPriceTick", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinPriceTick.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinQuantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinQuantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerFeeBps", wireType)
			}
			m.MakerFeeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MakerFeeBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerFeeBps", wireType)
			}
			m.TakerFeeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TakerFeeBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= MarketStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAtBlock", wireType)
			}
			m.CreatedAtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAtBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SpotOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpotOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpotOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = append(m.Owner[:0], dAtA[iNdEx:postIndex]...)
			if m.Owner == nil {
				m.Owner = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Side", wireType)
			}
			m.Side = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Side |= Side(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= OrderType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tif", wireType)
			}
			m.Tif = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tif |= TimeInForce(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Quantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilledQuantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FilledQuantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LockedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedHeight", wireType)
			}
			m.CreatedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seq", wireType)
			}
			m.Seq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAtBlock", wireType)
			}
			m.ExpiresAtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAtBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SpotFill) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SpotFill: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SpotFill: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FillSeq", wireType)
			}
			m.FillSeq = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FillSeq |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerOrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TakerOrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerOrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MakerOrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Taker", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Taker = append(m.Taker[:0], dAtA[iNdEx:postIndex]...)
			if m.Taker == nil {
				m.Taker = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Maker", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Maker = append(m.Maker[:0], dAtA[iNdEx:postIndex]...)
			if m.Maker == nil {
				m.Maker = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerSide", wireType)
			}
			m.TakerSide = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TakerSide |= Side(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Quantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TakerFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MakerFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OrderbookLevel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSpot
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderbookLevel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderbookLevel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalQuantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSpot
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSpot
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalQuantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderCount", wireType)
			}
			m.OrderCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OrderCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSpot(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSpot
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSpot(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSpot
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSpot
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSpot
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSpot
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSpot
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSpot        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSpot          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSpot = fmt.Errorf("proto: unexpected end of group")
)
