// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ltrstchain/ltrstdex/tx.proto

package types

import (
	context "context"
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgCreateSpotMarket struct {
	// authority is either gov (default) or an address matching the
	// module authority in module.proto. Checked against
	// Params.gov_only_market_creation.
	Authority    string                      `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Ticker       string                      `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	BaseDenom    string                      `protobuf:"bytes,3,opt,name=base_denom,json=baseDenom,proto3" json:"base_denom,omitempty"`
	QuoteDenom   string                      `protobuf:"bytes,4,opt,name=quote_denom,json=quoteDenom,proto3" json:"quote_denom,omitempty"`
	MinPriceTick cosmossdk_io_math.LegacyDec `protobuf:"bytes,5,opt,name=min_price_tick,json=minPriceTick,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_price_tick"`
	MinQuantity  cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=min_quantity,json=minQuantity,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_quantity"`
	MakerFeeBps  uint32                      `protobuf:"varint,7,opt,name=maker_fee_bps,json=makerFeeBps,proto3" json:"maker_fee_bps,omitempty"`
	TakerFeeBps  uint32                      `protobuf:"varint,8,opt,name=taker_fee_bps,json=takerFeeBps,proto3" json:"taker_fee_bps,omitempty"`
	// initial_status is the status the market will be created in.
	// Typically PRE_OPEN or ACTIVE.
	InitialStatus MarketStatus `protobuf:"varint,9,opt,name=initial_status,json=initialStatus,proto3,enum=ltrstchain.ltrstdex.MarketStatus" json:"initial_status,omitempty"`
}

func (m *MsgCreateSpotMarket) Reset()         { *m = MsgCreateSpotMarket{} }
func (m *MsgCreateSpotMarket) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSpotMarket) ProtoMessage()    {}
func (*MsgCreateSpotMarket) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{2}
}
func (m *MsgCreateSpotMarket) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSpotMarket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSpotMarket.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSpotMarket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSpotMarket.Merge(m, src)
}
func (m *MsgCreateSpotMarket) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSpotMarket) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSpotMarket.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSpotMarket proto.InternalMessageInfo

func (m *MsgCreateSpotMarket) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgCreateSpotMarket) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *MsgCreateSpotMarket) GetBaseDenom() string {
	if m != nil {
		return m.BaseDenom
	}
	return ""
}

func (m *MsgCreateSpotMarket) GetQuoteDenom() string {
	if m != nil {
		return m.QuoteDenom
	}
	return ""
}

func (m *MsgCreateSpotMarket) GetMakerFeeBps() uint32 {
	if m != nil {
		return m.MakerFeeBps
	}
	return 0
}

func (m *MsgCreateSpotMarket) GetTakerFeeBps() uint32 {
	if m != nil {
		return m.TakerFeeBps
	}
	return 0
}

func (m *MsgCreateSpotMarket) GetInitialStatus() MarketStatus {
	if m != nil {
		return m.InitialStatus
	}
	return MarketStatus_MARKET_STATUS_UNSPECIFIED
}

type MsgCreateSpotMarketResponse struct {
	MarketId uint64 `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
}

func (m *MsgCreateSpotMarketResponse) Reset()         { *m = MsgCreateSpotMarketResponse{} }
func (m *MsgCreateSpotMarketResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateSpotMarketResponse) ProtoMessage()    {}
func (*MsgCreateSpotMarketResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{3}
}
func (m *MsgCreateSpotMarketResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateSpotMarketResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateSpotMarketResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateSpotMarketResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateSpotMarketResponse.Merge(m, src)
}
func (m *MsgCreateSpotMarketResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateSpotMarketResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateSpotMarketResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateSpotMarketResponse proto.InternalMessageInfo

func (m *MsgCreateSpotMarketResponse) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

type MsgUpdateSpotMarketStatus struct {
	Authority string       `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MarketId  uint64       `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	NewStatus MarketStatus `protobuf:"varint,3,opt,name=new_status,json=newStatus,proto3,enum=ltrstchain.ltrstdex.MarketStatus" json:"new_status,omitempty"`
}

func (m *MsgUpdateSpotMarketStatus) Reset()         { *m = MsgUpdateSpotMarketStatus{} }
func (m *MsgUpdateSpotMarketStatus) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSpotMarketStatus) ProtoMessage()    {}
func (*MsgUpdateSpotMarketStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{4}
}
func (m *MsgUpdateSpotMarketStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSpotMarketStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSpotMarketStatus.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSpotMarketStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSpotMarketStatus.Merge(m, src)
}
func (m *MsgUpdateSpotMarketStatus) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSpotMarketStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSpotMarketStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSpotMarketStatus proto.InternalMessageInfo

func (m *MsgUpdateSpotMarketStatus) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateSpotMarketStatus) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *MsgUpdateSpotMarketStatus) GetNewStatus() MarketStatus {
	if m != nil {
		return m.NewStatus
	}
	return MarketStatus_MARKET_STATUS_UNSPECIFIED
}

type MsgUpdateSpotMarketStatusResponse struct {
}

func (m *MsgUpdateSpotMarketStatusResponse) Reset()         { *m = MsgUpdateSpotMarketStatusResponse{} }
func (m *MsgUpdateSpotMarketStatusResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateSpotMarketStatusResponse) ProtoMessage()    {}
func (*MsgUpdateSpotMarketStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{5}
}
func (m *MsgUpdateSpotMarketStatusResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateSpotMarketStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateSpotMarketStatusResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateSpotMarketStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateSpotMarketStatusResponse.Merge(m, src)
}
func (m *MsgUpdateSpotMarketStatusResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateSpotMarketStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateSpotMarketStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateSpotMarketStatusResponse proto.InternalMessageInfo

type MsgPlaceSpotOrder struct {
	Owner    string      `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	MarketId uint64      `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Side     Side        `protobuf:"varint,3,opt,name=side,proto3,enum=ltrstchain.ltrstdex.Side" json:"side,omitempty"`
	Type     OrderType   `protobuf:"varint,4,opt,name=type,proto3,enum=ltrstchain.ltrstdex.OrderType" json:"type,omitempty"`
	Tif      TimeInForce `protobuf:"varint,5,opt,name=tif,proto3,enum=ltrstchain.ltrstdex.TimeInForce" json:"tif,omitempty"`
	// price is the limit price in quote units per base unit. Required
	// for ORDER_TYPE_LIMIT; MUST be empty/"0" for ORDER_TYPE_MARKET.
	Price cosmossdk_io_math.LegacyDec `protobuf:"bytes,6,opt,name=price,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"price"`
	// quantity is the total base-asset quantity to trade.
	Quantity cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=quantity,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"quantity"`
	// expires_at_block is the optional auto-cancel height. 0 = never.
	ExpiresAtBlock int64 `protobuf:"varint,8,opt,name=expires_at_block,json=expiresAtBlock,proto3" json:"expires_at_block,omitempty"`
	// client_order_id is an optional owner-chosen tag. Up to 64 chars.
	// Not required to be unique. Echoed back in the response and the
	// SpotOrder for UI correlation.
	ClientOrderId string `protobuf:"bytes,9,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
}

func (m *MsgPlaceSpotOrder) Reset()         { *m = MsgPlaceSpotOrder{} }
func (m *MsgPlaceSpotOrder) String() string { return proto.CompactTextString(m) }
func (*MsgPlaceSpotOrder) ProtoMessage()    {}
func (*MsgPlaceSpotOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{6}
}
func (m *MsgPlaceSpotOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPlaceSpotOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPlaceSpotOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPlaceSpotOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlaceSpotOrder.Merge(m, src)
}
func (m *MsgPlaceSpotOrder) XXX_Size() int {
	return m.Size()
}
func (m *MsgPlaceSpotOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlaceSpotOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlaceSpotOrder proto.InternalMessageInfo

func (m *MsgPlaceSpotOrder) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgPlaceSpotOrder) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *MsgPlaceSpotOrder) GetSide() Side {
	if m != nil {
		return m.Side
	}
	return Side_SIDE_UNSPECIFIED
}

func (m *MsgPlaceSpotOrder) GetType() OrderType {
	if m != nil {
		return m.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (m *MsgPlaceSpotOrder) GetTif() TimeInForce {
	if m != nil {
		return m.Tif
	}
	return TimeInForce_TIF_GTC
}

func (m *MsgPlaceSpotOrder) GetExpiresAtBlock() int64 {
	if m != nil {
		return m.ExpiresAtBlock
	}
	return 0
}

func (m *MsgPlaceSpotOrder) GetClientOrderId() string {
	if m != nil {
		return m.ClientOrderId
	}
	return ""
}

type MsgPlaceSpotOrderResponse struct {
	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	// filled_quantity is how much of the order matched immediately.
	FilledQuantity cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=filled_quantity,json=filledQuantity,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"filled_quantity"`
	// resting_quantity is the remainder (if any) left on the book.
	RestingQuantity cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=resting_quantity,json=restingQuantity,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"resting_quantity"`
}

func (m *MsgPlaceSpotOrderResponse) Reset()         { *m = MsgPlaceSpotOrderResponse{} }
func (m *MsgPlaceSpotOrderResponse) String() string { return proto.CompactTextString(m) }
func (*MsgPlaceSpotOrderResponse) ProtoMessage()    {}
func (*MsgPlaceSpotOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{7}
}
func (m *MsgPlaceSpotOrderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgPlaceSpotOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgPlaceSpotOrderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgPlaceSpotOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgPlaceSpotOrderResponse.Merge(m, src)
}
func (m *MsgPlaceSpotOrderResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgPlaceSpotOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgPlaceSpotOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgPlaceSpotOrderResponse proto.InternalMessageInfo

func (m *MsgPlaceSpotOrderResponse) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type MsgCancelSpotOrder struct {
	// authority is the order owner, OR the gov/module authority if
	// cancelling a non-owned order (used for HALTED status cleanup).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	MarketId  uint64 `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	OrderId   string `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (m *MsgCancelSpotOrder) Reset()         { *m = MsgCancelSpotOrder{} }
func (m *MsgCancelSpotOrder) String() string { return proto.CompactTextString(m) }
func (*MsgCancelSpotOrder) ProtoMessage()    {}
func (*MsgCancelSpotOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{8}
}
func (m *MsgCancelSpotOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelSpotOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelSpotOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelSpotOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelSpotOrder.Merge(m, src)
}
func (m *MsgCancelSpotOrder) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelSpotOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelSpotOrder.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelSpotOrder proto.InternalMessageInfo

func (m *MsgCancelSpotOrder) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgCancelSpotOrder) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

func (m *MsgCancelSpotOrder) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

type MsgCancelSpotOrderResponse struct {
}

func (m *MsgCancelSpotOrderResponse) Reset()         { *m = MsgCancelSpotOrderResponse{} }
func (m *MsgCancelSpotOrderResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelSpotOrderResponse) ProtoMessage()    {}
func (*MsgCancelSpotOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{9}
}
func (m *MsgCancelSpotOrderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelSpotOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelSpotOrderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelSpotOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelSpotOrderResponse.Merge(m, src)
}
func (m *MsgCancelSpotOrderResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelSpotOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelSpotOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelSpotOrderResponse proto.InternalMessageInfo

type MsgCancelAllSpotOrders struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// market_id optionally scopes the cancel to a single market. 0 =
	// cancel across every market.
	MarketId uint64 `protobuf:"varint,2,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
}

func (m *MsgCancelAllSpotOrders) Reset()         { *m = MsgCancelAllSpotOrders{} }
func (m *MsgCancelAllSpotOrders) String() string { return proto.CompactTextString(m) }
func (*MsgCancelAllSpotOrders) ProtoMessage()    {}
func (*MsgCancelAllSpotOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{10}
}
func (m *MsgCancelAllSpotOrders) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelAllSpotOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelAllSpotOrders.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelAllSpotOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelAllSpotOrders.Merge(m, src)
}
func (m *MsgCancelAllSpotOrders) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelAllSpotOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelAllSpotOrders.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelAllSpotOrders proto.InternalMessageInfo

func (m *MsgCancelAllSpotOrders) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgCancelAllSpotOrders) GetMarketId() uint64 {
	if m != nil {
		return m.MarketId
	}
	return 0
}

type MsgCancelAllSpotOrdersResponse struct {
	CancelledCount uint32 `protobuf:"varint,1,opt,name=cancelled_count,json=cancelledCount,proto3" json:"cancelled_count,omitempty"`
}

func (m *MsgCancelAllSpotOrdersResponse) Reset()         { *m = MsgCancelAllSpotOrdersResponse{} }
func (m *MsgCancelAllSpotOrdersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCancelAllSpotOrdersResponse) ProtoMessage()    {}
func (*MsgCancelAllSpotOrdersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb643ab3dd50fa7, []int{11}
}
func (m *MsgCancelAllSpotOrdersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCancelAllSpotOrdersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCancelAllSpotOrdersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCancelAllSpotOrdersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCancelAllSpotOrdersResponse.Merge(m, src)
}
func (m *MsgCancelAllSpotOrdersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCancelAllSpotOrdersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCancelAllSpotOrdersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCancelAllSpotOrdersResponse proto.InternalMessageInfo

func (m *MsgCancelAllSpotOrdersResponse) GetCancelledCount() uint32 {
	if m != nil {
		return m.CancelledCount
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "ltrstchain.ltrstdex.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "ltrstchain.ltrstdex.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateSpotMarket)(nil), "ltrstchain.ltrstdex.MsgCreateSpotMarket")
	proto.RegisterType((*MsgCreateSpotMarketResponse)(nil), "ltrstchain.ltrstdex.MsgCreateSpotMarketResponse")
	proto.RegisterType((*MsgUpdateSpotMarketStatus)(nil), "ltrstchain.ltrstdex.MsgUpdateSpotMarketStatus")
	proto.RegisterType((*MsgUpdateSpotMarketStatusResponse)(nil), "ltrstchain.ltrstdex.MsgUpdateSpotMarketStatusResponse")
	proto.RegisterType((*MsgPlaceSpotOrder)(nil), "ltrstchain.ltrstdex.MsgPlaceSpotOrder")
	proto.RegisterType((*MsgPlaceSpotOrderResponse)(nil), "ltrstchain.ltrstdex.MsgPlaceSpotOrderResponse")
	proto.RegisterType((*MsgCancelSpotOrder)(nil), "ltrstchain.ltrstdex.MsgCancelSpotOrder")
	proto.RegisterType((*MsgCancelSpotOrderResponse)(nil), "ltrstchain.ltrstdex.MsgCancelSpotOrderResponse")
	proto.RegisterType((*MsgCancelAllSpotOrders)(nil), "ltrstchain.ltrstdex.MsgCancelAllSpotOrders")
	proto.RegisterType((*MsgCancelAllSpotOrdersResponse)(nil), "ltrstchain.ltrstdex.MsgCancelAllSpotOrdersResponse")
}

func init() { proto.RegisterFile("ltrstchain/ltrstdex/tx.proto", fileDescriptor_bdb643ab3dd50fa7) }

var fileDescriptor_bdb643ab3dd50fa7 = []byte{
	// 1073 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0xd6, 0xf9, 0xe7, 0x97, 0xc6, 0x4e, 0x37, 0x55, 0xea, 0x6c, 0x8a, 0xe3, 0x6e, 0xa1,
	0x31, 0xa1, 0xb5, 0xc1, 0x15, 0x11, 0x04, 0x04, 0xc4, 0xad, 0x22, 0x22, 0x35, 0x10, 0x36, 0xe1,
	0xc2, 0x65, 0xb5, 0xd9, 0x9d, 0x6c, 0x46, 0xf6, 0xee, 0x6c, 0x77, 0xc6, 0x24, 0xb9, 0x55, 0x9c,
	0x10, 0x27, 0x3e, 0x03, 0x27, 0x8e, 0x91, 0xe0, 0x0b, 0x20, 0x2e, 0x3d, 0x56, 0x88, 0x03, 0xe2,
	0x50, 0xa1, 0xe4, 0x90, 0x6f, 0xc0, 0x0d, 0x09, 0xcd, 0xcc, 0x7a, 0x37, 0x6b, 0xaf, 0x13, 0xa7,
	0x82, 0x4b, 0xe2, 0xf9, 0xbd, 0xdf, 0xfb, 0x33, 0x6f, 0xde, 0x6f, 0x76, 0xe0, 0x76, 0x9b, 0x85,
	0x94, 0xd9, 0xfb, 0x16, 0xf6, 0xeb, 0xe2, 0xa7, 0x83, 0x0e, 0xeb, 0xec, 0xb0, 0x16, 0x84, 0x84,
	0x11, 0x75, 0x36, 0xb1, 0xd6, 0xba, 0x56, 0xed, 0x86, 0xe5, 0x61, 0x9f, 0xd4, 0xc5, 0x5f, 0xc9,
	0xd3, 0x6e, 0xd9, 0x84, 0x7a, 0x84, 0xd6, 0x3d, 0xea, 0xd6, 0xbf, 0x7e, 0x87, 0xff, 0x8b, 0x0c,
	0xf3, 0xd2, 0x60, 0x8a, 0x55, 0x5d, 0x2e, 0x22, 0xd3, 0x4d, 0x97, 0xb8, 0x44, 0xe2, 0xfc, 0x57,
	0x84, 0x56, 0xb2, 0xea, 0x09, 0xac, 0xd0, 0xf2, 0xba, 0x7e, 0xe5, 0x2c, 0x06, 0x0d, 0x08, 0x93,
	0x76, 0xfd, 0x57, 0x05, 0x8a, 0x9b, 0xd4, 0xfd, 0x32, 0x70, 0x2c, 0x86, 0xb6, 0x84, 0xa7, 0xba,
	0x02, 0x79, 0xab, 0xc3, 0xf6, 0x49, 0x88, 0xd9, 0x51, 0x49, 0xa9, 0x28, 0xd5, 0x7c, 0xb3, 0xf4,
	0xdb, 0xcf, 0x0f, 0x6e, 0x46, 0x05, 0xad, 0x39, 0x4e, 0x88, 0x28, 0xdd, 0x66, 0x21, 0xf6, 0x5d,
	0x23, 0xa1, 0xaa, 0x1f, 0xc1, 0xb8, 0xcc, 0x5d, 0xba, 0x56, 0x51, 0xaa, 0x53, 0x8d, 0x85, 0x5a,
	0x46, 0x43, 0x6a, 0x32, 0x49, 0x33, 0xff, 0xfc, 0xe5, 0xe2, 0xc8, 0x8f, 0x67, 0xc7, 0xcb, 0x8a,
	0x11, 0x79, 0xad, 0xbe, 0xf7, 0xcd, 0xd9, 0xf1, 0x72, 0x12, 0xef, 0xbb, 0xb3, 0xe3, 0xe5, 0x37,
	0xce, 0x95, 0x7f, 0x98, 0x6c, 0xa0, 0xa7, 0x62, 0x7d, 0x1e, 0x6e, 0xf5, 0x40, 0x06, 0xa2, 0x01,
	0xf1, 0x29, 0xd2, 0xbf, 0x1d, 0x85, 0xd9, 0x4d, 0xea, 0x3e, 0x0a, 0x91, 0xc5, 0xd0, 0x76, 0x40,
	0xd8, 0xa6, 0x15, 0xb6, 0x10, 0x7b, 0xe5, 0x4d, 0xce, 0xc1, 0x38, 0xc3, 0x76, 0x0b, 0x85, 0x62,
	0x93, 0x79, 0x23, 0x5a, 0xa9, 0xaf, 0x01, 0xec, 0x5a, 0x14, 0x99, 0x0e, 0xf2, 0x89, 0x57, 0xca,
	0x09, 0x5b, 0x9e, 0x23, 0x8f, 0x39, 0xa0, 0x2e, 0xc2, 0xd4, 0xd3, 0x0e, 0x61, 0x5d, 0xfb, 0xa8,
	0xb0, 0x83, 0x80, 0x24, 0x61, 0x03, 0x0a, 0x1e, 0xf6, 0xcd, 0x20, 0xc4, 0x36, 0x32, 0x79, 0xcc,
	0xd2, 0x98, 0x28, 0xea, 0x2e, 0xef, 0xd3, 0x9f, 0x2f, 0x17, 0x17, 0x64, 0x61, 0xd4, 0x69, 0xd5,
	0x30, 0xa9, 0x7b, 0x16, 0xdb, 0xaf, 0x3d, 0x41, 0xae, 0x65, 0x1f, 0x3d, 0x46, 0xb6, 0x71, 0xdd,
	0xc3, 0xfe, 0x16, 0xf7, 0xdc, 0xc1, 0x76, 0x4b, 0x5d, 0x07, 0xbe, 0x36, 0x9f, 0x76, 0x2c, 0x9f,
	0xf1, 0xdd, 0x8d, 0x0f, 0x1f, 0x68, 0xca, 0xc3, 0xfe, 0x17, 0x91, 0x9f, 0xaa, 0xc3, 0xb4, 0x67,
	0xb5, 0x50, 0x68, 0xee, 0x21, 0x64, 0xee, 0x06, 0xb4, 0x34, 0x51, 0x51, 0xaa, 0xd3, 0xc6, 0x94,
	0x00, 0xd7, 0x11, 0x6a, 0x06, 0x94, 0x73, 0x58, 0x8a, 0x33, 0x29, 0x39, 0xec, 0x1c, 0xe7, 0x53,
	0x28, 0x60, 0x1f, 0x33, 0x6c, 0xb5, 0x4d, 0xca, 0x2c, 0xd6, 0xa1, 0xa5, 0x7c, 0x45, 0xa9, 0x16,
	0x1a, 0x77, 0x32, 0xe7, 0x43, 0x9e, 0xcf, 0xb6, 0x20, 0x1a, 0xd3, 0x91, 0xa3, 0x5c, 0xae, 0x7e,
	0xd8, 0x3f, 0x21, 0x6f, 0x0e, 0x9c, 0x90, 0xde, 0x23, 0xd7, 0x57, 0x61, 0x21, 0x03, 0xee, 0x4e,
	0x8a, 0xba, 0x00, 0x79, 0x4f, 0x20, 0x26, 0x76, 0xc4, 0x44, 0x8c, 0x1a, 0x93, 0x12, 0xd8, 0x70,
	0xf4, 0xbf, 0x15, 0x98, 0x8f, 0x47, 0x2c, 0x71, 0x96, 0x75, 0xbd, 0xf2, 0x30, 0xa5, 0x52, 0x5e,
	0x4b, 0xa7, 0x54, 0x3f, 0x01, 0xf0, 0xd1, 0x41, 0xb7, 0x65, 0xb9, 0x61, 0x5b, 0x96, 0xf7, 0xd1,
	0x41, 0xd4, 0xae, 0x66, 0x7f, 0xbb, 0xea, 0x97, 0x08, 0xaa, 0x77, 0x6b, 0xfa, 0x5d, 0xb8, 0x33,
	0xd0, 0x18, 0x8b, 0xec, 0x9f, 0x1c, 0xdc, 0xd8, 0xa4, 0xee, 0x56, 0xdb, 0xb2, 0x05, 0xe9, 0xf3,
	0xd0, 0x41, 0xa1, 0x5a, 0x83, 0x31, 0x72, 0xe0, 0xa3, 0xf0, 0xd2, 0x8e, 0x48, 0xda, 0xc5, 0xdd,
	0x78, 0x00, 0xa3, 0x14, 0x3b, 0x28, 0xea, 0xc3, 0x7c, 0x66, 0x1f, 0xb6, 0xb1, 0x83, 0x0c, 0x41,
	0x53, 0x1b, 0x30, 0xca, 0x8e, 0x02, 0x24, 0x84, 0x56, 0x68, 0x94, 0x33, 0xe9, 0xa2, 0xca, 0x9d,
	0xa3, 0x00, 0x19, 0x82, 0xab, 0x36, 0x20, 0xc7, 0xf0, 0x9e, 0xd0, 0x5d, 0xa1, 0x51, 0xc9, 0x74,
	0xd9, 0xc1, 0x1e, 0xda, 0xf0, 0xd7, 0x49, 0x68, 0x23, 0x83, 0x93, 0xd5, 0xf7, 0x61, 0x4c, 0x48,
	0xf6, 0x2a, 0x22, 0x93, 0x1e, 0xea, 0xc7, 0x30, 0x19, 0x4b, 0x74, 0x62, 0x78, 0xef, 0xd8, 0x49,
	0xad, 0xc2, 0x0c, 0x3a, 0x0c, 0x70, 0x88, 0xa8, 0x69, 0x31, 0x73, 0xb7, 0x4d, 0xec, 0x96, 0x90,
	0x5f, 0xce, 0x28, 0x44, 0xf8, 0x1a, 0x6b, 0x72, 0x54, 0xbd, 0x07, 0x45, 0xbb, 0x8d, 0x91, 0xcf,
	0x4c, 0xc2, 0xf7, 0xcc, 0xfb, 0x9b, 0x17, 0x37, 0xd0, 0xb4, 0x84, 0x45, 0x27, 0x36, 0x9c, 0xd5,
	0x15, 0x3e, 0x30, 0xf2, 0x34, 0xf8, 0xb0, 0x2c, 0x0d, 0x1c, 0x96, 0xf4, 0x49, 0xeb, 0xbf, 0x4b,
	0x75, 0xa4, 0xd1, 0x58, 0x58, 0xf3, 0x30, 0x19, 0xa7, 0x15, 0xa3, 0x60, 0x4c, 0x10, 0x99, 0x50,
	0x7d, 0x02, 0xc5, 0x3d, 0xdc, 0x6e, 0x23, 0x27, 0xb9, 0xad, 0xae, 0x0d, 0xdf, 0x8a, 0x82, 0xf4,
	0x8d, 0x2f, 0xac, 0xcf, 0x60, 0x26, 0x44, 0x94, 0x61, 0xdf, 0x4d, 0xc2, 0xe5, 0x86, 0x0f, 0x57,
	0x8c, 0x9c, 0xbb, 0xf1, 0xf4, 0x5f, 0x14, 0x50, 0xf9, 0x8d, 0x61, 0xf9, 0x36, 0x6a, 0x27, 0x73,
	0xfd, 0xbf, 0xa8, 0xfd, 0x7c, 0x93, 0x72, 0xa9, 0x26, 0xad, 0x7e, 0xd0, 0x2f, 0xe3, 0xea, 0xe0,
	0x5b, 0x2f, 0x5d, 0xac, 0x7e, 0x1b, 0xb4, 0x7e, 0x34, 0x16, 0xee, 0x0f, 0x0a, 0xcc, 0xc5, 0xe6,
	0xb5, 0x76, 0xc2, 0xa0, 0xff, 0xa9, 0x7a, 0xe5, 0x16, 0x92, 0xc1, 0xba, 0x7f, 0x49, 0xf9, 0xa9,
	0x4a, 0xf4, 0x0d, 0x28, 0x67, 0x5b, 0xe2, 0x09, 0x5b, 0x82, 0xa2, 0x2d, 0xcc, 0x7c, 0x92, 0x6c,
	0xd2, 0xf1, 0x99, 0xa8, 0x7a, 0xda, 0x28, 0xc4, 0xf0, 0x23, 0x8e, 0x36, 0x7e, 0x1a, 0x83, 0xdc,
	0x26, 0x75, 0xd5, 0x5d, 0xb8, 0x9e, 0x7a, 0xf2, 0xbc, 0x9e, 0x7d, 0xaf, 0xa6, 0xdf, 0x14, 0xda,
	0xfd, 0x61, 0x58, 0x71, 0x51, 0x3e, 0xcc, 0xf4, 0xbd, 0x3a, 0xaa, 0x83, 0x22, 0xf4, 0x32, 0xb5,
	0xb7, 0x87, 0x65, 0xc6, 0xf9, 0x9e, 0x29, 0x30, 0x37, 0xe0, 0xfb, 0x54, 0xbb, 0xb8, 0xf0, 0x5e,
	0xbe, 0xb6, 0x72, 0x35, 0x7e, 0x5c, 0xc2, 0x3e, 0x14, 0x7a, 0xbe, 0x01, 0xf7, 0x06, 0x45, 0x4a,
	0xf3, 0xb4, 0xda, 0x70, 0xbc, 0x38, 0x53, 0x0b, 0x8a, 0xbd, 0xb2, 0x5c, 0x1a, 0xd8, 0xb1, 0x34,
	0x51, 0xab, 0x0f, 0x49, 0x8c, 0x93, 0x1d, 0xc0, 0x6c, 0x96, 0x42, 0xde, 0xba, 0x38, 0x4e, 0x8a,
	0xac, 0x3d, 0xbc, 0x02, 0xb9, 0x9b, 0x58, 0x1b, 0x7b, 0xc6, 0x1f, 0xc8, 0xcd, 0x77, 0x9f, 0x9f,
	0x94, 0x95, 0x17, 0x27, 0x65, 0xe5, 0xaf, 0x93, 0xb2, 0xf2, 0xfd, 0x69, 0x79, 0xe4, 0xc5, 0x69,
	0x79, 0xe4, 0x8f, 0xd3, 0xf2, 0xc8, 0x57, 0x0b, 0xd9, 0x42, 0xe2, 0x9f, 0x33, 0xba, 0x3b, 0x2e,
	0x9e, 0xf8, 0x0f, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xbb, 0xd6, 0xfd, 0xb6, 0x0c, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams updates the module parameters. Gov-gated.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// CreateSpotMarket lists a new spot trading pair. Gov-gated in
	// Phase 1 (Params.gov_only_market_creation = true).
	CreateSpotMarket(ctx context.Context, in *MsgCreateSpotMarket, opts ...grpc.CallOption) (*MsgCreateSpotMarketResponse, error)
	// UpdateSpotMarketStatus transitions a market between PRE_OPEN /
	// ACTIVE / POST_ONLY / PAUSED / HALTED. Gov-gated.
	UpdateSpotMarketStatus(ctx context.Context, in *MsgUpdateSpotMarketStatus, opts ...grpc.CallOption) (*MsgUpdateSpotMarketStatusResponse, error)
	// PlaceSpotOrder places a new limit or market order. Immediate
	// matching happens inside this handler.
	PlaceSpotOrder(ctx context.Context, in *MsgPlaceSpotOrder, opts ...grpc.CallOption) (*MsgPlaceSpotOrderResponse, error)
	// CancelSpotOrder cancels a single live order. Allowed to the
	// order owner or gov.
	CancelSpotOrder(ctx context.Context, in *MsgCancelSpotOrder, opts ...grpc.CallOption) (*MsgCancelSpotOrderResponse, error)
	// CancelAllSpotOrders cancels every live order owned by the
	// sender, optionally scoped to a single market.
	CancelAllSpotOrders(ctx context.Context, in *MsgCancelAllSpotOrders, opts ...grpc.CallOption) (*MsgCancelAllSpotOrdersResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.ltrstdex.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateSpotMarket(ctx context.Context, in *MsgCreateSpotMarket, opts ...grpc.CallOption) (*MsgCreateSpotMarketResponse, error) {
	out := new(MsgCreateSpotMarketResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.ltrstdex.Msg/CreateSpotMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateSpotMarketStatus(ctx context.Context, in *MsgUpdateSpotMarketStatus, opts ...grpc.CallOption) (*MsgUpdateSpotMarketStatusResponse, error) {
	out := new(MsgUpdateSpotMarketStatusResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.ltrstdex.Msg/UpdateSpotMarketStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PlaceSpotOrder(ctx context.Context, in *MsgPlaceSpotOrder, opts ...grpc.CallOption) (*MsgPlaceSpotOrderResponse, error) {
	out := new(MsgPlaceSpotOrderResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.ltrstdex.Msg/PlaceSpotOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelSpotOrder(ctx context.Context, in *MsgCancelSpotOrder, opts ...grpc.CallOption) (*MsgCancelSpotOrderResponse, error) {
	out := new(MsgCancelSpotOrderResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.ltrstdex.Msg/CancelSpotOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelAllSpotOrders(ctx context.Context, in *MsgCancelAllSpotOrders, opts ...grpc.CallOption) (*MsgCancelAllSpotOrdersResponse, error) {
	out := new(MsgCancelAllSpotOrdersResponse)
	err := c.cc.Invoke(ctx, "/ltrstchain.ltrstdex.Msg/CancelAllSpotOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams updates the module parameters. Gov-gated.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// CreateSpotMarket lists a new spot trading pair. Gov-gated in
	// Phase 1 (Params.gov_only_market_creation = true).
	CreateSpotMarket(context.Context, *MsgCreateSpotMarket) (*MsgCreateSpotMarketResponse, error)
	// UpdateSpotMarketStatus transitions a market between PRE_OPEN /
	// ACTIVE / POST_ONLY / PAUSED / HALTED. Gov-gated.
	UpdateSpotMarketStatus(context.Context, *MsgUpdateSpotMarketStatus) (*MsgUpdateSpotMarketStatusResponse, error)
	// PlaceSpotOrder places a new limit or market order. Immediate
	// matching happens inside this handler.
	PlaceSpotOrder(context.Context, *MsgPlaceSpotOrder) (*MsgPlaceSpotOrderResponse, error)
	// CancelSpotOrder cancels a single live order. Allowed to the
	// order owner or gov.
	CancelSpotOrder(context.Context, *MsgCancelSpotOrder) (*MsgCancelSpotOrderResponse, error)
	// CancelAllSpotOrders cancels every live order owned by the
	// sender, optionally scoped to a single market.
	CancelAllSpotOrders(context.Context, *MsgCancelAllSpotOrders) (*MsgCancelAllSpotOrdersResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreateSpotMarket(ctx context.Context, req *MsgCreateSpotMarket) (*MsgCreateSpotMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSpotMarket not implemented")
}
func (*UnimplementedMsgServer) UpdateSpotMarketStatus(ctx context.Context, req *MsgUpdateSpotMarketStatus) (*MsgUpdateSpotMarketStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSpotMarketStatus not implemented")
}
func (*UnimplementedMsgServer) PlaceSpotOrder(ctx context.Context, req *MsgPlaceSpotOrder) (*MsgPlaceSpotOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceSpotOrder not implemented")
}
func (*UnimplementedMsgServer) CancelSpotOrder(ctx context.Context, req *MsgCancelSpotOrder) (*MsgCancelSpotOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelSpotOrder not implemented")
}
func (*UnimplementedMsgServer) CancelAllSpotOrders(ctx context.Context, req *MsgCancelAllSpotOrders) (*MsgCancelAllSpotOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelAllSpotOrders not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.ltrstdex.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateSpotMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateSpotMarket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateSpotMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.ltrstdex.Msg/CreateSpotMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateSpotMarket(ctx, req.(*MsgCreateSpotMarket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateSpotMarketStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateSpotMarketStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateSpotMarketStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.ltrstdex.Msg/UpdateSpotMarketStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateSpotMarketStatus(ctx, req.(*MsgUpdateSpotMarketStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PlaceSpotOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgPlaceSpotOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PlaceSpotOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.ltrstdex.Msg/PlaceSpotOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PlaceSpotOrder(ctx, req.(*MsgPlaceSpotOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelSpotOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelSpotOrder)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelSpotOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.ltrstdex.Msg/CancelSpotOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelSpotOrder(ctx, req.(*MsgCancelSpotOrder))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelAllSpotOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCancelAllSpotOrders)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelAllSpotOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ltrstchain.ltrstdex.Msg/CancelAllSpotOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelAllSpotOrders(ctx, req.(*MsgCancelAllSpotOrders))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ltrstchain.ltrstdex.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateSpotMarket",
			Handler:    _Msg_CreateSpotMarket_Handler,
		},
		{
			MethodName: "UpdateSpotMarketStatus",
			Handler:    _Msg_UpdateSpotMarketStatus_Handler,
		},
		{
			MethodName: "PlaceSpotOrder",
			Handler:    _Msg_PlaceSpotOrder_Handler,
		},
		{
			MethodName: "CancelSpotOrder",
			Handler:    _Msg_CancelSpotOrder_Handler,
		},
		{
			MethodName: "CancelAllSpotOrders",
			Handler:    _Msg_CancelAllSpotOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ltrstchain/ltrstdex/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateSpotMarket) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSpotMarket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSpotMarket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.InitialStatus != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.InitialStatus))
		i--
		dAtA[i] = 0x48
	}
	if m.TakerFeeBps != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TakerFeeBps))
		i--
		dAtA[i] = 0x40
	}
	if m.MakerFeeBps != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MakerFeeBps))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.MinQuantity.Size()
		i -= size
		if _, err := m.MinQuantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MinPriceTick.Size()
		i -= size
		if _, err := m.MinPriceTick.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.QuoteDenom) > 0 {
		i -= len(m.QuoteDenom)
		copy(dAtA[i:], m.QuoteDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.QuoteDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BaseDenom) > 0 {
		i -= len(m.BaseDenom)
		copy(dAtA[i:], m.BaseDenom)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BaseDenom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Ticker) > 0 {
		i -= len(m.Ticker)
		copy(dAtA[i:], m.Ticker)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Ticker)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateSpotMarketResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateSpotMarketResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateSpotMarketResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MarketId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSpotMarketStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSpotMarketStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSpotMarketStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.NewStatus != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.NewStatus))
		i--
		dAtA[i] = 0x18
	}
	if m.MarketId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateSpotMarketStatusResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateSpotMarketStatusResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateSpotMarketStatusResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgPlaceSpotOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPlaceSpotOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPlaceSpotOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ClientOrderId) > 0 {
		i -= len(m.ClientOrderId)
		copy(dAtA[i:], m.ClientOrderId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ClientOrderId)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ExpiresAtBlock != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExpiresAtBlock))
		i--
		dAtA[i] = 0x40
	}
	{
		size := m.Quantity.Size()
		i -= size
		if _, err := m.Quantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.Price.Size()
		i -= size
		if _, err := m.Price.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.Tif != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Tif))
		i--
		dAtA[i] = 0x28
	}
	if m.Type != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x20
	}
	if m.Side != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Side))
		i--
		dAtA[i] = 0x18
	}
	if m.MarketId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgPlaceSpotOrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgPlaceSpotOrderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgPlaceSpotOrderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.RestingQuantity.Size()
		i -= size
		if _, err := m.RestingQuantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.FilledQuantity.Size()
		i -= size
		if _, err := m.FilledQuantity.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.OrderId) > 0 {
		i -= len(m.OrderId)
		copy(dAtA[i:], m.OrderId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OrderId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelSpotOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelSpotOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelSpotOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OrderId) > 0 {
		i -= len(m.OrderId)
		copy(dAtA[i:], m.OrderId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.OrderId)))
		i--
		dAtA[i] = 0x1a
	}
	if m.MarketId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelSpotOrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelSpotOrderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelSpotOrderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCancelAllSpotOrders) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelAllSpotOrders) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelAllSpotOrders) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MarketId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MarketId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCancelAllSpotOrdersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCancelAllSpotOrdersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCancelAllSpotOrdersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CancelledCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.CancelledCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateSpotMarket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Ticker)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BaseDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.QuoteDenom)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.MinPriceTick.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.MinQuantity.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.MakerFeeBps != 0 {
		n += 1 + sovTx(uint64(m.MakerFeeBps))
	}
	if m.TakerFeeBps != 0 {
		n += 1 + sovTx(uint64(m.TakerFeeBps))
	}
	if m.InitialStatus != 0 {
		n += 1 + sovTx(uint64(m.InitialStatus))
	}
	return n
}

func (m *MsgCreateSpotMarketResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MarketId != 0 {
		n += 1 + sovTx(uint64(m.MarketId))
	}
	return n
}

func (m *MsgUpdateSpotMarketStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MarketId != 0 {
		n += 1 + sovTx(uint64(m.MarketId))
	}
	if m.NewStatus != 0 {
		n += 1 + sovTx(uint64(m.NewStatus))
	}
	return n
}

func (m *MsgUpdateSpotMarketStatusResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgPlaceSpotOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MarketId != 0 {
		n += 1 + sovTx(uint64(m.MarketId))
	}
	if m.Side != 0 {
		n += 1 + sovTx(uint64(m.Side))
	}
	if m.Type != 0 {
		n += 1 + sovTx(uint64(m.Type))
	}
	if m.Tif != 0 {
		n += 1 + sovTx(uint64(m.Tif))
	}
	l = m.Price.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.Quantity.Size()
	n += 1 + l + sovTx(uint64(l))
	if m.ExpiresAtBlock != 0 {
		n += 1 + sovTx(uint64(m.ExpiresAtBlock))
	}
	l = len(m.ClientOrderId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgPlaceSpotOrderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.FilledQuantity.Size()
	n += 1 + l + sovTx(uint64(l))
	l = m.RestingQuantity.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgCancelSpotOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MarketId != 0 {
		n += 1 + sovTx(uint64(m.MarketId))
	}
	l = len(m.OrderId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCancelSpotOrderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCancelAllSpotOrders) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MarketId != 0 {
		n += 1 + sovTx(uint64(m.MarketId))
	}
	return n
}

func (m *MsgCancelAllSpotOrdersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CancelledCount != 0 {
		n += 1 + sovTx(uint64(m.CancelledCount))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateSpotMarket) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSpotMarket: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSpotMarket: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ticker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ticker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BaseDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QuoteDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QuoteDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPriceTick", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinPriceTick.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinQuantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinQuantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MakerFeeBps", wireType)
			}
			m.MakerFeeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MakerFeeBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TakerFeeBps", wireType)
			}
			m.TakerFeeBps = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TakerFeeBps |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialStatus", wireType)
			}
			m.InitialStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialStatus |= MarketStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateSpotMarketResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateSpotMarketResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateSpotMarketResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSpotMarketStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSpotMarketStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSpotMarketStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewStatus", wireType)
			}
			m.NewStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NewStatus |= MarketStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateSpotMarketStatusResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateSpotMarketStatusResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateSpotMarketStatusResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPlaceSpotOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPlaceSpotOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPlaceSpotOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Side", wireType)
			}
			m.Side = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Side |= Side(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= OrderType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tif", wireType)
			}
			m.Tif = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tif |= TimeInForce(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Quantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiresAtBlock", wireType)
			}
			m.ExpiresAtBlock = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpiresAtBlock |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientOrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientOrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgPlaceSpotOrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgPlaceSpotOrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgPlaceSpotOrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FilledQuantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FilledQuantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RestingQuantity", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RestingQuantity.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelSpotOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelSpotOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelSpotOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelSpotOrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelSpotOrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelSpotOrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelAllSpotOrders) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelAllSpotOrders: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelAllSpotOrders: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarketId", wireType)
			}
			m.MarketId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MarketId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCancelAllSpotOrdersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCancelAllSpotOrdersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCancelAllSpotOrdersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CancelledCount", wireType)
			}
			m.CancelledCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CancelledCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
