// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: ltrstchain/ltrstchain/privacy.proto

package ltrstchain

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MsgPrivacy_ShieldedTransfer_FullMethodName = "/ltrstchain.ltrstchain.MsgPrivacy/ShieldedTransfer"
	MsgPrivacy_ShieldedDeposit_FullMethodName  = "/ltrstchain.ltrstchain.MsgPrivacy/ShieldedDeposit"
	MsgPrivacy_ShieldedWithdraw_FullMethodName = "/ltrstchain.ltrstchain.MsgPrivacy/ShieldedWithdraw"
)

// MsgPrivacyClient is the client API for MsgPrivacy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgPrivacyClient interface {
	// ShieldedTransfer records a shielded commitment on-chain. The sender
	// submits the commitment bytes, the nullifier, optional field commitments,
	// and optional field openings. The module rejects any transaction whose
	// nullifier has already been observed (double-spend prevention) and any
	// opening whose (value, salt) does not hash to its declared field commitment.
	ShieldedTransfer(ctx context.Context, in *MsgShieldedTransfer, opts ...grpc.CallOption) (*MsgShieldedTransferResponse, error)
	// ShieldedDeposit records a shielded commitment AND atomically escrows the
	// supplied coins from the depositor into the shielded-pool module account.
	// Rejects on double-spend (nullifier already seen), invalid opening, or
	// insufficient balance. The deposit amount becomes part of the shielded
	// pool's TVL and can only be released via ShieldedWithdraw.
	ShieldedDeposit(ctx context.Context, in *MsgShieldedDeposit, opts ...grpc.CallOption) (*MsgShieldedDepositResponse, error)
	// ShieldedWithdraw releases coins from the shielded-pool module account to
	// the specified recipient. INTERIM MODE: the tx signer must be the module
	// authority (governance) and supply a previously-unused nullifier. Once
	// zk-SNARK verification lands on-chain, the authority check is replaced
	// with proof-of-knowledge of a commitment opening.
	ShieldedWithdraw(ctx context.Context, in *MsgShieldedWithdraw, opts ...grpc.CallOption) (*MsgShieldedWithdrawResponse, error)
}

type msgPrivacyClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgPrivacyClient(cc grpc.ClientConnInterface) MsgPrivacyClient {
	return &msgPrivacyClient{cc}
}

func (c *msgPrivacyClient) ShieldedTransfer(ctx context.Context, in *MsgShieldedTransfer, opts ...grpc.CallOption) (*MsgShieldedTransferResponse, error) {
	out := new(MsgShieldedTransferResponse)
	err := c.cc.Invoke(ctx, MsgPrivacy_ShieldedTransfer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgPrivacyClient) ShieldedDeposit(ctx context.Context, in *MsgShieldedDeposit, opts ...grpc.CallOption) (*MsgShieldedDepositResponse, error) {
	out := new(MsgShieldedDepositResponse)
	err := c.cc.Invoke(ctx, MsgPrivacy_ShieldedDeposit_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgPrivacyClient) ShieldedWithdraw(ctx context.Context, in *MsgShieldedWithdraw, opts ...grpc.CallOption) (*MsgShieldedWithdrawResponse, error) {
	out := new(MsgShieldedWithdrawResponse)
	err := c.cc.Invoke(ctx, MsgPrivacy_ShieldedWithdraw_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgPrivacyServer is the server API for MsgPrivacy service.
// All implementations must embed UnimplementedMsgPrivacyServer
// for forward compatibility
type MsgPrivacyServer interface {
	// ShieldedTransfer records a shielded commitment on-chain. The sender
	// submits the commitment bytes, the nullifier, optional field commitments,
	// and optional field openings. The module rejects any transaction whose
	// nullifier has already been observed (double-spend prevention) and any
	// opening whose (value, salt) does not hash to its declared field commitment.
	ShieldedTransfer(context.Context, *MsgShieldedTransfer) (*MsgShieldedTransferResponse, error)
	// ShieldedDeposit records a shielded commitment AND atomically escrows the
	// supplied coins from the depositor into the shielded-pool module account.
	// Rejects on double-spend (nullifier already seen), invalid opening, or
	// insufficient balance. The deposit amount becomes part of the shielded
	// pool's TVL and can only be released via ShieldedWithdraw.
	ShieldedDeposit(context.Context, *MsgShieldedDeposit) (*MsgShieldedDepositResponse, error)
	// ShieldedWithdraw releases coins from the shielded-pool module account to
	// the specified recipient. INTERIM MODE: the tx signer must be the module
	// authority (governance) and supply a previously-unused nullifier. Once
	// zk-SNARK verification lands on-chain, the authority check is replaced
	// with proof-of-knowledge of a commitment opening.
	ShieldedWithdraw(context.Context, *MsgShieldedWithdraw) (*MsgShieldedWithdrawResponse, error)
	mustEmbedUnimplementedMsgPrivacyServer()
}

// UnimplementedMsgPrivacyServer must be embedded to have forward compatible implementations.
type UnimplementedMsgPrivacyServer struct {
}

func (UnimplementedMsgPrivacyServer) ShieldedTransfer(context.Context, *MsgShieldedTransfer) (*MsgShieldedTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShieldedTransfer not implemented")
}
func (UnimplementedMsgPrivacyServer) ShieldedDeposit(context.Context, *MsgShieldedDeposit) (*MsgShieldedDepositResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShieldedDeposit not implemented")
}
func (UnimplementedMsgPrivacyServer) ShieldedWithdraw(context.Context, *MsgShieldedWithdraw) (*MsgShieldedWithdrawResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShieldedWithdraw not implemented")
}
func (UnimplementedMsgPrivacyServer) mustEmbedUnimplementedMsgPrivacyServer() {}

// UnsafeMsgPrivacyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgPrivacyServer will
// result in compilation errors.
type UnsafeMsgPrivacyServer interface {
	mustEmbedUnimplementedMsgPrivacyServer()
}

func RegisterMsgPrivacyServer(s grpc.ServiceRegistrar, srv MsgPrivacyServer) {
	s.RegisterService(&MsgPrivacy_ServiceDesc, srv)
}

func _MsgPrivacy_ShieldedTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgShieldedTransfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgPrivacyServer).ShieldedTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgPrivacy_ShieldedTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgPrivacyServer).ShieldedTransfer(ctx, req.(*MsgShieldedTransfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgPrivacy_ShieldedDeposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgShieldedDeposit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgPrivacyServer).ShieldedDeposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgPrivacy_ShieldedDeposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgPrivacyServer).ShieldedDeposit(ctx, req.(*MsgShieldedDeposit))
	}
	return interceptor(ctx, in, info, handler)
}

func _MsgPrivacy_ShieldedWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgShieldedWithdraw)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgPrivacyServer).ShieldedWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MsgPrivacy_ShieldedWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgPrivacyServer).ShieldedWithdraw(ctx, req.(*MsgShieldedWithdraw))
	}
	return interceptor(ctx, in, info, handler)
}

// MsgPrivacy_ServiceDesc is the grpc.ServiceDesc for MsgPrivacy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MsgPrivacy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ltrstchain.ltrstchain.MsgPrivacy",
	HandlerType: (*MsgPrivacyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShieldedTransfer",
			Handler:    _MsgPrivacy_ShieldedTransfer_Handler,
		},
		{
			MethodName: "ShieldedDeposit",
			Handler:    _MsgPrivacy_ShieldedDeposit_Handler,
		},
		{
			MethodName: "ShieldedWithdraw",
			Handler:    _MsgPrivacy_ShieldedWithdraw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ltrstchain/ltrstchain/privacy.proto",
}

const (
	QueryPrivacy_Commitment_FullMethodName    = "/ltrstchain.ltrstchain.QueryPrivacy/Commitment"
	QueryPrivacy_NullifierUsed_FullMethodName = "/ltrstchain.ltrstchain.QueryPrivacy/NullifierUsed"
	QueryPrivacy_MerkleRoot_FullMethodName    = "/ltrstchain.ltrstchain.QueryPrivacy/MerkleRoot"
)

// QueryPrivacyClient is the client API for QueryPrivacy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryPrivacyClient interface {
	// Commitment returns a stored commitment by its 32-byte commit bytes.
	Commitment(ctx context.Context, in *QueryCommitmentRequest, opts ...grpc.CallOption) (*QueryCommitmentResponse, error)
	// NullifierUsed returns whether a given nullifier has already been spent.
	NullifierUsed(ctx context.Context, in *QueryNullifierUsedRequest, opts ...grpc.CallOption) (*QueryNullifierUsedResponse, error)
	// MerkleRoot returns the current rolling Merkle accumulator root.
	MerkleRoot(ctx context.Context, in *QueryMerkleRootRequest, opts ...grpc.CallOption) (*QueryMerkleRootResponse, error)
}

type queryPrivacyClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryPrivacyClient(cc grpc.ClientConnInterface) QueryPrivacyClient {
	return &queryPrivacyClient{cc}
}

func (c *queryPrivacyClient) Commitment(ctx context.Context, in *QueryCommitmentRequest, opts ...grpc.CallOption) (*QueryCommitmentResponse, error) {
	out := new(QueryCommitmentResponse)
	err := c.cc.Invoke(ctx, QueryPrivacy_Commitment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryPrivacyClient) NullifierUsed(ctx context.Context, in *QueryNullifierUsedRequest, opts ...grpc.CallOption) (*QueryNullifierUsedResponse, error) {
	out := new(QueryNullifierUsedResponse)
	err := c.cc.Invoke(ctx, QueryPrivacy_NullifierUsed_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryPrivacyClient) MerkleRoot(ctx context.Context, in *QueryMerkleRootRequest, opts ...grpc.CallOption) (*QueryMerkleRootResponse, error) {
	out := new(QueryMerkleRootResponse)
	err := c.cc.Invoke(ctx, QueryPrivacy_MerkleRoot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryPrivacyServer is the server API for QueryPrivacy service.
// All implementations must embed UnimplementedQueryPrivacyServer
// for forward compatibility
type QueryPrivacyServer interface {
	// Commitment returns a stored commitment by its 32-byte commit bytes.
	Commitment(context.Context, *QueryCommitmentRequest) (*QueryCommitmentResponse, error)
	// NullifierUsed returns whether a given nullifier has already been spent.
	NullifierUsed(context.Context, *QueryNullifierUsedRequest) (*QueryNullifierUsedResponse, error)
	// MerkleRoot returns the current rolling Merkle accumulator root.
	MerkleRoot(context.Context, *QueryMerkleRootRequest) (*QueryMerkleRootResponse, error)
	mustEmbedUnimplementedQueryPrivacyServer()
}

// UnimplementedQueryPrivacyServer must be embedded to have forward compatible implementations.
type UnimplementedQueryPrivacyServer struct {
}

func (UnimplementedQueryPrivacyServer) Commitment(context.Context, *QueryCommitmentRequest) (*QueryCommitmentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Commitment not implemented")
}
func (UnimplementedQueryPrivacyServer) NullifierUsed(context.Context, *QueryNullifierUsedRequest) (*QueryNullifierUsedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NullifierUsed not implemented")
}
func (UnimplementedQueryPrivacyServer) MerkleRoot(context.Context, *QueryMerkleRootRequest) (*QueryMerkleRootResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerkleRoot not implemented")
}
func (UnimplementedQueryPrivacyServer) mustEmbedUnimplementedQueryPrivacyServer() {}

// UnsafeQueryPrivacyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryPrivacyServer will
// result in compilation errors.
type UnsafeQueryPrivacyServer interface {
	mustEmbedUnimplementedQueryPrivacyServer()
}

func RegisterQueryPrivacyServer(s grpc.ServiceRegistrar, srv QueryPrivacyServer) {
	s.RegisterService(&QueryPrivacy_ServiceDesc, srv)
}

func _QueryPrivacy_Commitment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryCommitmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryPrivacyServer).Commitment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryPrivacy_Commitment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryPrivacyServer).Commitment(ctx, req.(*QueryCommitmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryPrivacy_NullifierUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryNullifierUsedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryPrivacyServer).NullifierUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryPrivacy_NullifierUsed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryPrivacyServer).NullifierUsed(ctx, req.(*QueryNullifierUsedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueryPrivacy_MerkleRoot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMerkleRootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryPrivacyServer).MerkleRoot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueryPrivacy_MerkleRoot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryPrivacyServer).MerkleRoot(ctx, req.(*QueryMerkleRootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueryPrivacy_ServiceDesc is the grpc.ServiceDesc for QueryPrivacy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueryPrivacy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ltrstchain.ltrstchain.QueryPrivacy",
	HandlerType: (*QueryPrivacyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Commitment",
			Handler:    _QueryPrivacy_Commitment_Handler,
		},
		{
			MethodName: "NullifierUsed",
			Handler:    _QueryPrivacy_NullifierUsed_Handler,
		},
		{
			MethodName: "MerkleRoot",
			Handler:    _QueryPrivacy_MerkleRoot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ltrstchain/ltrstchain/privacy.proto",
}
