// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: ltrstchain/ltrstdex/query.proto

package ltrstdex

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Query_Params_FullMethodName             = "/ltrstchain.ltrstdex.Query/Params"
	Query_SpotMarket_FullMethodName         = "/ltrstchain.ltrstdex.Query/SpotMarket"
	Query_SpotMarketByTicker_FullMethodName = "/ltrstchain.ltrstdex.Query/SpotMarketByTicker"
	Query_SpotMarkets_FullMethodName        = "/ltrstchain.ltrstdex.Query/SpotMarkets"
	Query_SpotOrder_FullMethodName          = "/ltrstchain.ltrstdex.Query/SpotOrder"
	Query_SpotOrdersByOwner_FullMethodName  = "/ltrstchain.ltrstdex.Query/SpotOrdersByOwner"
	Query_SpotOrdersByMarket_FullMethodName = "/ltrstchain.ltrstdex.Query/SpotOrdersByMarket"
	Query_SpotOrderbook_FullMethodName      = "/ltrstchain.ltrstdex.Query/SpotOrderbook"
	Query_SpotFills_FullMethodName          = "/ltrstchain.ltrstdex.Query/SpotFills"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the module parameters.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// SpotMarket returns a single market by id.
	SpotMarket(ctx context.Context, in *QuerySpotMarketRequest, opts ...grpc.CallOption) (*QuerySpotMarketResponse, error)
	// SpotMarketByTicker returns a single market by ticker (e.g. "LTRST/USDC").
	SpotMarketByTicker(ctx context.Context, in *QuerySpotMarketByTickerRequest, opts ...grpc.CallOption) (*QuerySpotMarketResponse, error)
	// SpotMarkets returns the list of all markets (paginated).
	SpotMarkets(ctx context.Context, in *QuerySpotMarketsRequest, opts ...grpc.CallOption) (*QuerySpotMarketsResponse, error)
	// SpotOrder returns a single order by id.
	SpotOrder(ctx context.Context, in *QuerySpotOrderRequest, opts ...grpc.CallOption) (*QuerySpotOrderResponse, error)
	// SpotOrdersByOwner returns all live orders owned by address.
	SpotOrdersByOwner(ctx context.Context, in *QuerySpotOrdersByOwnerRequest, opts ...grpc.CallOption) (*QuerySpotOrdersByOwnerResponse, error)
	// SpotOrdersByMarket returns all live orders on a market.
	SpotOrdersByMarket(ctx context.Context, in *QuerySpotOrdersByMarketRequest, opts ...grpc.CallOption) (*QuerySpotOrdersByMarketResponse, error)
	// SpotOrderbook returns an aggregated depth snapshot for a market.
	SpotOrderbook(ctx context.Context, in *QuerySpotOrderbookRequest, opts ...grpc.CallOption) (*QuerySpotOrderbookResponse, error)
	// SpotFills returns fill history for a market.
	SpotFills(ctx context.Context, in *QuerySpotFillsRequest, opts ...grpc.CallOption) (*QuerySpotFillsResponse, error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, Query_Params_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpotMarket(ctx context.Context, in *QuerySpotMarketRequest, opts ...grpc.CallOption) (*QuerySpotMarketResponse, error) {
	out := new(QuerySpotMarketResponse)
	err := c.cc.Invoke(ctx, Query_SpotMarket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpotMarketByTicker(ctx context.Context, in *QuerySpotMarketByTickerRequest, opts ...grpc.CallOption) (*QuerySpotMarketResponse, error) {
	out := new(QuerySpotMarketResponse)
	err := c.cc.Invoke(ctx, Query_SpotMarketByTicker_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpotMarkets(ctx context.Context, in *QuerySpotMarketsRequest, opts ...grpc.CallOption) (*QuerySpotMarketsResponse, error) {
	out := new(QuerySpotMarketsResponse)
	err := c.cc.Invoke(ctx, Query_SpotMarkets_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpotOrder(ctx context.Context, in *QuerySpotOrderRequest, opts ...grpc.CallOption) (*QuerySpotOrderResponse, error) {
	out := new(QuerySpotOrderResponse)
	err := c.cc.Invoke(ctx, Query_SpotOrder_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpotOrdersByOwner(ctx context.Context, in *QuerySpotOrdersByOwnerRequest, opts ...grpc.CallOption) (*QuerySpotOrdersByOwnerResponse, error) {
	out := new(QuerySpotOrdersByOwnerResponse)
	err := c.cc.Invoke(ctx, Query_SpotOrdersByOwner_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpotOrdersByMarket(ctx context.Context, in *QuerySpotOrdersByMarketRequest, opts ...grpc.CallOption) (*QuerySpotOrdersByMarketResponse, error) {
	out := new(QuerySpotOrdersByMarketResponse)
	err := c.cc.Invoke(ctx, Query_SpotOrdersByMarket_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpotOrderbook(ctx context.Context, in *QuerySpotOrderbookRequest, opts ...grpc.CallOption) (*QuerySpotOrderbookResponse, error) {
	out := new(QuerySpotOrderbookResponse)
	err := c.cc.Invoke(ctx, Query_SpotOrderbook_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) SpotFills(ctx context.Context, in *QuerySpotFillsRequest, opts ...grpc.CallOption) (*QuerySpotFillsResponse, error) {
	out := new(QuerySpotFillsResponse)
	err := c.cc.Invoke(ctx, Query_SpotFills_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
// All implementations must embed UnimplementedQueryServer
// for forward compatibility
type QueryServer interface {
	// Params queries the module parameters.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// SpotMarket returns a single market by id.
	SpotMarket(context.Context, *QuerySpotMarketRequest) (*QuerySpotMarketResponse, error)
	// SpotMarketByTicker returns a single market by ticker (e.g. "LTRST/USDC").
	SpotMarketByTicker(context.Context, *QuerySpotMarketByTickerRequest) (*QuerySpotMarketResponse, error)
	// SpotMarkets returns the list of all markets (paginated).
	SpotMarkets(context.Context, *QuerySpotMarketsRequest) (*QuerySpotMarketsResponse, error)
	// SpotOrder returns a single order by id.
	SpotOrder(context.Context, *QuerySpotOrderRequest) (*QuerySpotOrderResponse, error)
	// SpotOrdersByOwner returns all live orders owned by address.
	SpotOrdersByOwner(context.Context, *QuerySpotOrdersByOwnerRequest) (*QuerySpotOrdersByOwnerResponse, error)
	// SpotOrdersByMarket returns all live orders on a market.
	SpotOrdersByMarket(context.Context, *QuerySpotOrdersByMarketRequest) (*QuerySpotOrdersByMarketResponse, error)
	// SpotOrderbook returns an aggregated depth snapshot for a market.
	SpotOrderbook(context.Context, *QuerySpotOrderbookRequest) (*QuerySpotOrderbookResponse, error)
	// SpotFills returns fill history for a market.
	SpotFills(context.Context, *QuerySpotFillsRequest) (*QuerySpotFillsResponse, error)
	mustEmbedUnimplementedQueryServer()
}

// UnimplementedQueryServer must be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (UnimplementedQueryServer) Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (UnimplementedQueryServer) SpotMarket(context.Context, *QuerySpotMarketRequest) (*QuerySpotMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpotMarket not implemented")
}
func (UnimplementedQueryServer) SpotMarketByTicker(context.Context, *QuerySpotMarketByTickerRequest) (*QuerySpotMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpotMarketByTicker not implemented")
}
func (UnimplementedQueryServer) SpotMarkets(context.Context, *QuerySpotMarketsRequest) (*QuerySpotMarketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpotMarkets not implemented")
}
func (UnimplementedQueryServer) SpotOrder(context.Context, *QuerySpotOrderRequest) (*QuerySpotOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpotOrder not implemented")
}
func (UnimplementedQueryServer) SpotOrdersByOwner(context.Context, *QuerySpotOrdersByOwnerRequest) (*QuerySpotOrdersByOwnerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpotOrdersByOwner not implemented")
}
func (UnimplementedQueryServer) SpotOrdersByMarket(context.Context, *QuerySpotOrdersByMarketRequest) (*QuerySpotOrdersByMarketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpotOrdersByMarket not implemented")
}
func (UnimplementedQueryServer) SpotOrderbook(context.Context, *QuerySpotOrderbookRequest) (*QuerySpotOrderbookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpotOrderbook not implemented")
}
func (UnimplementedQueryServer) SpotFills(context.Context, *QuerySpotFillsRequest) (*QuerySpotFillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpotFills not implemented")
}
func (UnimplementedQueryServer) mustEmbedUnimplementedQueryServer() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_Params_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpotMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpotMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpotMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SpotMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpotMarket(ctx, req.(*QuerySpotMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpotMarketByTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpotMarketByTickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpotMarketByTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SpotMarketByTicker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpotMarketByTicker(ctx, req.(*QuerySpotMarketByTickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpotMarkets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpotMarketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpotMarkets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SpotMarkets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpotMarkets(ctx, req.(*QuerySpotMarketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpotOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpotOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpotOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SpotOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpotOrder(ctx, req.(*QuerySpotOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpotOrdersByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpotOrdersByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpotOrdersByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SpotOrdersByOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpotOrdersByOwner(ctx, req.(*QuerySpotOrdersByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpotOrdersByMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpotOrdersByMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpotOrdersByMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SpotOrdersByMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpotOrdersByMarket(ctx, req.(*QuerySpotOrdersByMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpotOrderbook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpotOrderbookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpotOrderbook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SpotOrderbook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpotOrderbook(ctx, req.(*QuerySpotOrderbookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_SpotFills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySpotFillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).SpotFills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_SpotFills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).SpotFills(ctx, req.(*QuerySpotFillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ltrstchain.ltrstdex.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "SpotMarket",
			Handler:    _Query_SpotMarket_Handler,
		},
		{
			MethodName: "SpotMarketByTicker",
			Handler:    _Query_SpotMarketByTicker_Handler,
		},
		{
			MethodName: "SpotMarkets",
			Handler:    _Query_SpotMarkets_Handler,
		},
		{
			MethodName: "SpotOrder",
			Handler:    _Query_SpotOrder_Handler,
		},
		{
			MethodName: "SpotOrdersByOwner",
			Handler:    _Query_SpotOrdersByOwner_Handler,
		},
		{
			MethodName: "SpotOrdersByMarket",
			Handler:    _Query_SpotOrdersByMarket_Handler,
		},
		{
			MethodName: "SpotOrderbook",
			Handler:    _Query_SpotOrderbook_Handler,
		},
		{
			MethodName: "SpotFills",
			Handler:    _Query_SpotFills_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ltrstchain/ltrstdex/query.proto",
}
