// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package bridge

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_BridgeAsset                   protoreflect.MessageDescriptor
	fd_BridgeAsset_ibc_denom         protoreflect.FieldDescriptor
	fd_BridgeAsset_display_symbol    protoreflect.FieldDescriptor
	fd_BridgeAsset_display_name      protoreflect.FieldDescriptor
	fd_BridgeAsset_decimals          protoreflect.FieldDescriptor
	fd_BridgeAsset_source            protoreflect.FieldDescriptor
	fd_BridgeAsset_source_chain_id   protoreflect.FieldDescriptor
	fd_BridgeAsset_source_denom      protoreflect.FieldDescriptor
	fd_BridgeAsset_channel_id        protoreflect.FieldDescriptor
	fd_BridgeAsset_verified          protoreflect.FieldDescriptor
	fd_BridgeAsset_registered_height protoreflect.FieldDescriptor
	fd_BridgeAsset_updated_height    protoreflect.FieldDescriptor
)

func init() {
	file_ltrstchain_bridge_bridge_proto_init()
	md_BridgeAsset = File_ltrstchain_bridge_bridge_proto.Messages().ByName("BridgeAsset")
	fd_BridgeAsset_ibc_denom = md_BridgeAsset.Fields().ByName("ibc_denom")
	fd_BridgeAsset_display_symbol = md_BridgeAsset.Fields().ByName("display_symbol")
	fd_BridgeAsset_display_name = md_BridgeAsset.Fields().ByName("display_name")
	fd_BridgeAsset_decimals = md_BridgeAsset.Fields().ByName("decimals")
	fd_BridgeAsset_source = md_BridgeAsset.Fields().ByName("source")
	fd_BridgeAsset_source_chain_id = md_BridgeAsset.Fields().ByName("source_chain_id")
	fd_BridgeAsset_source_denom = md_BridgeAsset.Fields().ByName("source_denom")
	fd_BridgeAsset_channel_id = md_BridgeAsset.Fields().ByName("channel_id")
	fd_BridgeAsset_verified = md_BridgeAsset.Fields().ByName("verified")
	fd_BridgeAsset_registered_height = md_BridgeAsset.Fields().ByName("registered_height")
	fd_BridgeAsset_updated_height = md_BridgeAsset.Fields().ByName("updated_height")
}

var _ protoreflect.Message = (*fastReflection_BridgeAsset)(nil)

type fastReflection_BridgeAsset BridgeAsset

func (x *BridgeAsset) ProtoReflect() protoreflect.Message {
	return (*fastReflection_BridgeAsset)(x)
}

func (x *BridgeAsset) slowProtoReflect() protoreflect.Message {
	mi := &file_ltrstchain_bridge_bridge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_BridgeAsset_messageType fastReflection_BridgeAsset_messageType
var _ protoreflect.MessageType = fastReflection_BridgeAsset_messageType{}

type fastReflection_BridgeAsset_messageType struct{}

func (x fastReflection_BridgeAsset_messageType) Zero() protoreflect.Message {
	return (*fastReflection_BridgeAsset)(nil)
}
func (x fastReflection_BridgeAsset_messageType) New() protoreflect.Message {
	return new(fastReflection_BridgeAsset)
}
func (x fastReflection_BridgeAsset_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_BridgeAsset
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_BridgeAsset) Descriptor() protoreflect.MessageDescriptor {
	return md_BridgeAsset
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_BridgeAsset) Type() protoreflect.MessageType {
	return _fastReflection_BridgeAsset_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_BridgeAsset) New() protoreflect.Message {
	return new(fastReflection_BridgeAsset)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_BridgeAsset) Interface() protoreflect.ProtoMessage {
	return (*BridgeAsset)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_BridgeAsset) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.IbcDenom != "" {
		value := protoreflect.ValueOfString(x.IbcDenom)
		if !f(fd_BridgeAsset_ibc_denom, value) {
			return
		}
	}
	if x.DisplaySymbol != "" {
		value := protoreflect.ValueOfString(x.DisplaySymbol)
		if !f(fd_BridgeAsset_display_symbol, value) {
			return
		}
	}
	if x.DisplayName != "" {
		value := protoreflect.ValueOfString(x.DisplayName)
		if !f(fd_BridgeAsset_display_name, value) {
			return
		}
	}
	if x.Decimals != uint32(0) {
		value := protoreflect.ValueOfUint32(x.Decimals)
		if !f(fd_BridgeAsset_decimals, value) {
			return
		}
	}
	if x.Source != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.Source))
		if !f(fd_BridgeAsset_source, value) {
			return
		}
	}
	if x.SourceChainId != "" {
		value := protoreflect.ValueOfString(x.SourceChainId)
		if !f(fd_BridgeAsset_source_chain_id, value) {
			return
		}
	}
	if x.SourceDenom != "" {
		value := protoreflect.ValueOfString(x.SourceDenom)
		if !f(fd_BridgeAsset_source_denom, value) {
			return
		}
	}
	if x.ChannelId != "" {
		value := protoreflect.ValueOfString(x.ChannelId)
		if !f(fd_BridgeAsset_channel_id, value) {
			return
		}
	}
	if x.Verified != false {
		value := protoreflect.ValueOfBool(x.Verified)
		if !f(fd_BridgeAsset_verified, value) {
			return
		}
	}
	if x.RegisteredHeight != int64(0) {
		value := protoreflect.ValueOfInt64(x.RegisteredHeight)
		if !f(fd_BridgeAsset_registered_height, value) {
			return
		}
	}
	if x.UpdatedHeight != int64(0) {
		value := protoreflect.ValueOfInt64(x.UpdatedHeight)
		if !f(fd_BridgeAsset_updated_height, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_BridgeAsset) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "ltrstchain.bridge.BridgeAsset.ibc_denom":
		return x.IbcDenom != ""
	case "ltrstchain.bridge.BridgeAsset.display_symbol":
		return x.DisplaySymbol != ""
	case "ltrstchain.bridge.BridgeAsset.display_name":
		return x.DisplayName != ""
	case "ltrstchain.bridge.BridgeAsset.decimals":
		return x.Decimals != uint32(0)
	case "ltrstchain.bridge.BridgeAsset.source":
		return x.Source != 0
	case "ltrstchain.bridge.BridgeAsset.source_chain_id":
		return x.SourceChainId != ""
	case "ltrstchain.bridge.BridgeAsset.source_denom":
		return x.SourceDenom != ""
	case "ltrstchain.bridge.BridgeAsset.channel_id":
		return x.ChannelId != ""
	case "ltrstchain.bridge.BridgeAsset.verified":
		return x.Verified != false
	case "ltrstchain.bridge.BridgeAsset.registered_height":
		return x.RegisteredHeight != int64(0)
	case "ltrstchain.bridge.BridgeAsset.updated_height":
		return x.UpdatedHeight != int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ltrstchain.bridge.BridgeAsset"))
		}
		panic(fmt.Errorf("message ltrstchain.bridge.BridgeAsset does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_BridgeAsset) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "ltrstchain.bridge.BridgeAsset.ibc_denom":
		x.IbcDenom = ""
	case "ltrstchain.bridge.BridgeAsset.display_symbol":
		x.DisplaySymbol = ""
	case "ltrstchain.bridge.BridgeAsset.display_name":
		x.DisplayName = ""
	case "ltrstchain.bridge.BridgeAsset.decimals":
		x.Decimals = uint32(0)
	case "ltrstchain.bridge.BridgeAsset.source":
		x.Source = 0
	case "ltrstchain.bridge.BridgeAsset.source_chain_id":
		x.SourceChainId = ""
	case "ltrstchain.bridge.BridgeAsset.source_denom":
		x.SourceDenom = ""
	case "ltrstchain.bridge.BridgeAsset.channel_id":
		x.ChannelId = ""
	case "ltrstchain.bridge.BridgeAsset.verified":
		x.Verified = false
	case "ltrstchain.bridge.BridgeAsset.registered_height":
		x.RegisteredHeight = int64(0)
	case "ltrstchain.bridge.BridgeAsset.updated_height":
		x.UpdatedHeight = int64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ltrstchain.bridge.BridgeAsset"))
		}
		panic(fmt.Errorf("message ltrstchain.bridge.BridgeAsset does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_BridgeAsset) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "ltrstchain.bridge.BridgeAsset.ibc_denom":
		value := x.IbcDenom
		return protoreflect.ValueOfString(value)
	case "ltrstchain.bridge.BridgeAsset.display_symbol":
		value := x.DisplaySymbol
		return protoreflect.ValueOfString(value)
	case "ltrstchain.bridge.BridgeAsset.display_name":
		value := x.DisplayName
		return protoreflect.ValueOfString(value)
	case "ltrstchain.bridge.BridgeAsset.decimals":
		value := x.Decimals
		return protoreflect.ValueOfUint32(value)
	case "ltrstchain.bridge.BridgeAsset.source":
		value := x.Source
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "ltrstchain.bridge.BridgeAsset.source_chain_id":
		value := x.SourceChainId
		return protoreflect.ValueOfString(value)
	case "ltrstchain.bridge.BridgeAsset.source_denom":
		value := x.SourceDenom
		return protoreflect.ValueOfString(value)
	case "ltrstchain.bridge.BridgeAsset.channel_id":
		value := x.ChannelId
		return protoreflect.ValueOfString(value)
	case "ltrstchain.bridge.BridgeAsset.verified":
		value := x.Verified
		return protoreflect.ValueOfBool(value)
	case "ltrstchain.bridge.BridgeAsset.registered_height":
		value := x.RegisteredHeight
		return protoreflect.ValueOfInt64(value)
	case "ltrstchain.bridge.BridgeAsset.updated_height":
		value := x.UpdatedHeight
		return protoreflect.ValueOfInt64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ltrstchain.bridge.BridgeAsset"))
		}
		panic(fmt.Errorf("message ltrstchain.bridge.BridgeAsset does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_BridgeAsset) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "ltrstchain.bridge.BridgeAsset.ibc_denom":
		x.IbcDenom = value.Interface().(string)
	case "ltrstchain.bridge.BridgeAsset.display_symbol":
		x.DisplaySymbol = value.Interface().(string)
	case "ltrstchain.bridge.BridgeAsset.display_name":
		x.DisplayName = value.Interface().(string)
	case "ltrstchain.bridge.BridgeAsset.decimals":
		x.Decimals = uint32(value.Uint())
	case "ltrstchain.bridge.BridgeAsset.source":
		x.Source = (BridgeSource)(value.Enum())
	case "ltrstchain.bridge.BridgeAsset.source_chain_id":
		x.SourceChainId = value.Interface().(string)
	case "ltrstchain.bridge.BridgeAsset.source_denom":
		x.SourceDenom = value.Interface().(string)
	case "ltrstchain.bridge.BridgeAsset.channel_id":
		x.ChannelId = value.Interface().(string)
	case "ltrstchain.bridge.BridgeAsset.verified":
		x.Verified = value.Bool()
	case "ltrstchain.bridge.BridgeAsset.registered_height":
		x.RegisteredHeight = value.Int()
	case "ltrstchain.bridge.BridgeAsset.updated_height":
		x.UpdatedHeight = value.Int()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ltrstchain.bridge.BridgeAsset"))
		}
		panic(fmt.Errorf("message ltrstchain.bridge.BridgeAsset does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_BridgeAsset) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ltrstchain.bridge.BridgeAsset.ibc_denom":
		panic(fmt.Errorf("field ibc_denom of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.display_symbol":
		panic(fmt.Errorf("field display_symbol of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.display_name":
		panic(fmt.Errorf("field display_name of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.decimals":
		panic(fmt.Errorf("field decimals of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.source":
		panic(fmt.Errorf("field source of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.source_chain_id":
		panic(fmt.Errorf("field source_chain_id of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.source_denom":
		panic(fmt.Errorf("field source_denom of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.channel_id":
		panic(fmt.Errorf("field channel_id of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.verified":
		panic(fmt.Errorf("field verified of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.registered_height":
		panic(fmt.Errorf("field registered_height of message ltrstchain.bridge.BridgeAsset is not mutable"))
	case "ltrstchain.bridge.BridgeAsset.updated_height":
		panic(fmt.Errorf("field updated_height of message ltrstchain.bridge.BridgeAsset is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ltrstchain.bridge.BridgeAsset"))
		}
		panic(fmt.Errorf("message ltrstchain.bridge.BridgeAsset does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_BridgeAsset) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "ltrstchain.bridge.BridgeAsset.ibc_denom":
		return protoreflect.ValueOfString("")
	case "ltrstchain.bridge.BridgeAsset.display_symbol":
		return protoreflect.ValueOfString("")
	case "ltrstchain.bridge.BridgeAsset.display_name":
		return protoreflect.ValueOfString("")
	case "ltrstchain.bridge.BridgeAsset.decimals":
		return protoreflect.ValueOfUint32(uint32(0))
	case "ltrstchain.bridge.BridgeAsset.source":
		return protoreflect.ValueOfEnum(0)
	case "ltrstchain.bridge.BridgeAsset.source_chain_id":
		return protoreflect.ValueOfString("")
	case "ltrstchain.bridge.BridgeAsset.source_denom":
		return protoreflect.ValueOfString("")
	case "ltrstchain.bridge.BridgeAsset.channel_id":
		return protoreflect.ValueOfString("")
	case "ltrstchain.bridge.BridgeAsset.verified":
		return protoreflect.ValueOfBool(false)
	case "ltrstchain.bridge.BridgeAsset.registered_height":
		return protoreflect.ValueOfInt64(int64(0))
	case "ltrstchain.bridge.BridgeAsset.updated_height":
		return protoreflect.ValueOfInt64(int64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: ltrstchain.bridge.BridgeAsset"))
		}
		panic(fmt.Errorf("message ltrstchain.bridge.BridgeAsset does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_BridgeAsset) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in ltrstchain.bridge.BridgeAsset", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_BridgeAsset) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_BridgeAsset) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_BridgeAsset) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_BridgeAsset) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*BridgeAsset)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		l = len(x.IbcDenom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DisplaySymbol)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.DisplayName)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Decimals != 0 {
			n += 1 + runtime.Sov(uint64(x.Decimals))
		}
		if x.Source != 0 {
			n += 1 + runtime.Sov(uint64(x.Source))
		}
		l = len(x.SourceChainId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.SourceDenom)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.ChannelId)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Verified {
			n += 2
		}
		if x.RegisteredHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.RegisteredHeight))
		}
		if x.UpdatedHeight != 0 {
			n += 1 + runtime.Sov(uint64(x.UpdatedHeight))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*BridgeAsset)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.UpdatedHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.UpdatedHeight))
			i--
			dAtA[i] = 0x58
		}
		if x.RegisteredHeight != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.RegisteredHeight))
			i--
			dAtA[i] = 0x50
		}
		if x.Verified {
			i--
			if x.Verified {
				dAtA[i] = 1
			} else {
				dAtA[i] = 0
			}
			i--
			dAtA[i] = 0x48
		}
		if len(x.ChannelId) > 0 {
			i -= len(x.ChannelId)
			copy(dAtA[i:], x.ChannelId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ChannelId)))
			i--
			dAtA[i] = 0x42
		}
		if len(x.SourceDenom) > 0 {
			i -= len(x.SourceDenom)
			copy(dAtA[i:], x.SourceDenom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SourceDenom)))
			i--
			dAtA[i] = 0x3a
		}
		if len(x.SourceChainId) > 0 {
			i -= len(x.SourceChainId)
			copy(dAtA[i:], x.SourceChainId)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.SourceChainId)))
			i--
			dAtA[i] = 0x32
		}
		if x.Source != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Source))
			i--
			dAtA[i] = 0x28
		}
		if x.Decimals != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Decimals))
			i--
			dAtA[i] = 0x20
		}
		if len(x.DisplayName) > 0 {
			i -= len(x.DisplayName)
			copy(dAtA[i:], x.DisplayName)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DisplayName)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.DisplaySymbol) > 0 {
			i -= len(x.DisplaySymbol)
			copy(dAtA[i:], x.DisplaySymbol)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.DisplaySymbol)))
			i--
			dAtA[i] = 0x12
		}
		if len(x.IbcDenom) > 0 {
			i -= len(x.IbcDenom)
			copy(dAtA[i:], x.IbcDenom)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.IbcDenom)))
			i--
			dAtA[i] = 0xa
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*BridgeAsset)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: BridgeAsset: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: BridgeAsset: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field IbcDenom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.IbcDenom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DisplaySymbol", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DisplaySymbol = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field DisplayName", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.DisplayName = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Decimals", wireType)
				}
				x.Decimals = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Decimals |= uint32(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
				}
				x.Source = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Source |= BridgeSource(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 6:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SourceChainId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SourceChainId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 7:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SourceDenom", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.SourceDenom = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 8:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ChannelId", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ChannelId = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 9:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Verified", wireType)
				}
				var v int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				x.Verified = bool(v != 0)
			case 10:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field RegisteredHeight", wireType)
				}
				x.RegisteredHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.RegisteredHeight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 11:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field UpdatedHeight", wireType)
				}
				x.UpdatedHeight = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.UpdatedHeight |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: ltrstchain/bridge/bridge.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Source identifies which bridge brought an asset onto the chain. This
// is informational / UI-facing. The trust assumptions are enforced by
// governance when registering the entry.
type BridgeSource int32

const (
	BridgeSource_BRIDGE_SOURCE_UNSPECIFIED BridgeSource = 0
	// Noble issues native Circle USDC over IBC. Highest trust in the
	// Cosmos ecosystem for USDC.
	BridgeSource_BRIDGE_SOURCE_NOBLE BridgeSource = 1
	// Axelar is a Cosmos chain whose General Message Passing wraps EVM
	// (and other) assets into an IBC-transferable form.
	BridgeSource_BRIDGE_SOURCE_AXELAR BridgeSource = 2
	// Wormhole Gateway is a Cosmos chain that bridges non-Cosmos chains
	// (Solana, Ethereum pre-native, Sui, etc.) into IBC form.
	BridgeSource_BRIDGE_SOURCE_WORMHOLE BridgeSource = 3
	// Any other IBC counterparty not specifically one of the above.
	BridgeSource_BRIDGE_SOURCE_IBC_OTHER BridgeSource = 4
)

// Enum value maps for BridgeSource.
var (
	BridgeSource_name = map[int32]string{
		0: "BRIDGE_SOURCE_UNSPECIFIED",
		1: "BRIDGE_SOURCE_NOBLE",
		2: "BRIDGE_SOURCE_AXELAR",
		3: "BRIDGE_SOURCE_WORMHOLE",
		4: "BRIDGE_SOURCE_IBC_OTHER",
	}
	BridgeSource_value = map[string]int32{
		"BRIDGE_SOURCE_UNSPECIFIED": 0,
		"BRIDGE_SOURCE_NOBLE":       1,
		"BRIDGE_SOURCE_AXELAR":      2,
		"BRIDGE_SOURCE_WORMHOLE":    3,
		"BRIDGE_SOURCE_IBC_OTHER":   4,
	}
)

func (x BridgeSource) Enum() *BridgeSource {
	p := new(BridgeSource)
	*p = x
	return p
}

func (x BridgeSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BridgeSource) Descriptor() protoreflect.EnumDescriptor {
	return file_ltrstchain_bridge_bridge_proto_enumTypes[0].Descriptor()
}

func (BridgeSource) Type() protoreflect.EnumType {
	return &file_ltrstchain_bridge_bridge_proto_enumTypes[0]
}

func (x BridgeSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BridgeSource.Descriptor instead.
func (BridgeSource) EnumDescriptor() ([]byte, []int) {
	return file_ltrstchain_bridge_bridge_proto_rawDescGZIP(), []int{0}
}

// BridgeAsset is the on-chain registry record for an IBC-bridged
// asset. It ties the opaque ibc/<hash> denom users see in x/bank to
// human-meaningful display metadata and an origin attestation.
type BridgeAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ibc_denom is the canonical bank denomination, e.g.
	// "ibc/498A0751C7A53C569BE0F84EE4E6FA3B9D6C3B2FBEDFBF37EA0F67F8E56BDBC".
	// It is the hash-derived denom that x/ibc-transfer writes into
	// x/bank on receipt.
	IbcDenom string `protobuf:"bytes,1,opt,name=ibc_denom,json=ibcDenom,proto3" json:"ibc_denom,omitempty"`
	// display_symbol is the short ticker used in UIs (e.g. "USDC").
	DisplaySymbol string `protobuf:"bytes,2,opt,name=display_symbol,json=displaySymbol,proto3" json:"display_symbol,omitempty"`
	// display_name is the long name used in UIs (e.g. "USD Coin (Noble)").
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// decimals is the number of decimal places the source chain uses.
	// Most stablecoins use 6; ETH uses 18.
	Decimals uint32 `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// source identifies the bridge category (see BridgeSource).
	Source BridgeSource `protobuf:"varint,5,opt,name=source,proto3,enum=ltrstchain.bridge.BridgeSource" json:"source,omitempty"`
	// source_chain_id is the IBC counterparty chain id that originated
	// this asset (e.g. "noble-1", "axelar-dojo-1", "gateway-1").
	SourceChainId string `protobuf:"bytes,6,opt,name=source_chain_id,json=sourceChainId,proto3" json:"source_chain_id,omitempty"`
	// source_denom is the denom on the source chain, before any wrapping
	// (e.g. "uusdc" on Noble, "uusdc" on Axelar after conversion from
	// ERC-20, "solana-usdc" on Wormhole Gateway).
	SourceDenom string `protobuf:"bytes,7,opt,name=source_denom,json=sourceDenom,proto3" json:"source_denom,omitempty"`
	// channel_id is the ICS-04 channel id on THIS chain that the asset
	// arrives through (e.g. "channel-0"). Packets via any other channel
	// that hash to the same ibc_denom are still honoured by x/bank, but
	// the registry canonicalises one blessed path.
	ChannelId string `protobuf:"bytes,8,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// verified flags assets that have passed governance-level scrutiny.
	// UIs are encouraged to hide unverified assets by default.
	Verified bool `protobuf:"varint,9,opt,name=verified,proto3" json:"verified,omitempty"`
	// registered_height records the chain height at which this record
	// was first written. Useful for auditing registry drift.
	RegisteredHeight int64 `protobuf:"varint,10,opt,name=registered_height,json=registeredHeight,proto3" json:"registered_height,omitempty"`
	// updated_height records the height of the last mutation.
	UpdatedHeight int64 `protobuf:"varint,11,opt,name=updated_height,json=updatedHeight,proto3" json:"updated_height,omitempty"`
}

func (x *BridgeAsset) Reset() {
	*x = BridgeAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ltrstchain_bridge_bridge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BridgeAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BridgeAsset) ProtoMessage() {}

// Deprecated: Use BridgeAsset.ProtoReflect.Descriptor instead.
func (*BridgeAsset) Descriptor() ([]byte, []int) {
	return file_ltrstchain_bridge_bridge_proto_rawDescGZIP(), []int{0}
}

func (x *BridgeAsset) GetIbcDenom() string {
	if x != nil {
		return x.IbcDenom
	}
	return ""
}

func (x *BridgeAsset) GetDisplaySymbol() string {
	if x != nil {
		return x.DisplaySymbol
	}
	return ""
}

func (x *BridgeAsset) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *BridgeAsset) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *BridgeAsset) GetSource() BridgeSource {
	if x != nil {
		return x.Source
	}
	return BridgeSource_BRIDGE_SOURCE_UNSPECIFIED
}

func (x *BridgeAsset) GetSourceChainId() string {
	if x != nil {
		return x.SourceChainId
	}
	return ""
}

func (x *BridgeAsset) GetSourceDenom() string {
	if x != nil {
		return x.SourceDenom
	}
	return ""
}

func (x *BridgeAsset) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *BridgeAsset) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *BridgeAsset) GetRegisteredHeight() int64 {
	if x != nil {
		return x.RegisteredHeight
	}
	return 0
}

func (x *BridgeAsset) GetUpdatedHeight() int64 {
	if x != nil {
		return x.UpdatedHeight
	}
	return 0
}

var File_ltrstchain_bridge_bridge_proto protoreflect.FileDescriptor

var file_ltrstchain_bridge_bridge_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6c, 0x74, 0x72, 0x73, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x11, 0x6c, 0x74, 0x72, 0x73, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x1a, 0x11, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x03, 0x0a,
	0x0b, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x69, 0x62, 0x63, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x62, 0x63, 0x44, 0x65, 0x6e, 0x6f, 0x6d, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x5f, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x53, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12,
	0x37, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x6c, 0x74, 0x72, 0x73, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x21, 0x0a, 0x0c, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x64, 0x65, 0x6e, 0x6f, 0x6d,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x65,
	0x6e, 0x6f, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x2b,
	0x0a, 0x11, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x5f, 0x68, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x65, 0x64, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x48, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x3a, 0x04, 0xe8, 0xa0, 0x1f, 0x01, 0x2a, 0x99, 0x01, 0x0a, 0x0c, 0x42, 0x72, 0x69,
	0x64, 0x67, 0x65, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x19, 0x42, 0x52, 0x49,
	0x44, 0x47, 0x45, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x42, 0x52, 0x49, 0x44,
	0x47, 0x45, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x4e, 0x4f, 0x42, 0x4c, 0x45, 0x10,
	0x01, 0x12, 0x18, 0x0a, 0x14, 0x42, 0x52, 0x49, 0x44, 0x47, 0x45, 0x5f, 0x53, 0x4f, 0x55, 0x52,
	0x43, 0x45, 0x5f, 0x41, 0x58, 0x45, 0x4c, 0x41, 0x52, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x42,
	0x52, 0x49, 0x44, 0x47, 0x45, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x57, 0x4f, 0x52,
	0x4d, 0x48, 0x4f, 0x4c, 0x45, 0x10, 0x03, 0x12, 0x1b, 0x0a, 0x17, 0x42, 0x52, 0x49, 0x44, 0x47,
	0x45, 0x5f, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x5f, 0x49, 0x42, 0x43, 0x5f, 0x4f, 0x54, 0x48,
	0x45, 0x52, 0x10, 0x04, 0x42, 0xab, 0x01, 0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x2e, 0x6c, 0x74, 0x72,
	0x73, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2e, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0x42, 0x0b,
	0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x20, 0x6c,
	0x74, 0x72, 0x73, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6c, 0x74,
	0x72, 0x73, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x2f, 0x62, 0x72, 0x69, 0x64, 0x67, 0x65, 0xa2,
	0x02, 0x03, 0x4c, 0x42, 0x58, 0xaa, 0x02, 0x11, 0x4c, 0x74, 0x72, 0x73, 0x74, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x2e, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0xca, 0x02, 0x11, 0x4c, 0x74, 0x72, 0x73,
	0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x42, 0x72, 0x69, 0x64, 0x67, 0x65, 0xe2, 0x02, 0x1d,
	0x4c, 0x74, 0x72, 0x73, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5c, 0x42, 0x72, 0x69, 0x64, 0x67,
	0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x12,
	0x4c, 0x74, 0x72, 0x73, 0x74, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x3a, 0x3a, 0x42, 0x72, 0x69, 0x64,
	0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ltrstchain_bridge_bridge_proto_rawDescOnce sync.Once
	file_ltrstchain_bridge_bridge_proto_rawDescData = file_ltrstchain_bridge_bridge_proto_rawDesc
)

func file_ltrstchain_bridge_bridge_proto_rawDescGZIP() []byte {
	file_ltrstchain_bridge_bridge_proto_rawDescOnce.Do(func() {
		file_ltrstchain_bridge_bridge_proto_rawDescData = protoimpl.X.CompressGZIP(file_ltrstchain_bridge_bridge_proto_rawDescData)
	})
	return file_ltrstchain_bridge_bridge_proto_rawDescData
}

var file_ltrstchain_bridge_bridge_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ltrstchain_bridge_bridge_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ltrstchain_bridge_bridge_proto_goTypes = []interface{}{
	(BridgeSource)(0),   // 0: ltrstchain.bridge.BridgeSource
	(*BridgeAsset)(nil), // 1: ltrstchain.bridge.BridgeAsset
}
var file_ltrstchain_bridge_bridge_proto_depIdxs = []int32{
	0, // 0: ltrstchain.bridge.BridgeAsset.source:type_name -> ltrstchain.bridge.BridgeSource
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ltrstchain_bridge_bridge_proto_init() }
func file_ltrstchain_bridge_bridge_proto_init() {
	if File_ltrstchain_bridge_bridge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ltrstchain_bridge_bridge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BridgeAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ltrstchain_bridge_bridge_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ltrstchain_bridge_bridge_proto_goTypes,
		DependencyIndexes: file_ltrstchain_bridge_bridge_proto_depIdxs,
		EnumInfos:         file_ltrstchain_bridge_bridge_proto_enumTypes,
		MessageInfos:      file_ltrstchain_bridge_bridge_proto_msgTypes,
	}.Build()
	File_ltrstchain_bridge_bridge_proto = out.File
	file_ltrstchain_bridge_bridge_proto_rawDesc = nil
	file_ltrstchain_bridge_bridge_proto_goTypes = nil
	file_ltrstchain_bridge_bridge_proto_depIdxs = nil
}
