// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: ltrstchain/bridge/tx.proto

package bridge

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Msg_UpdateParams_FullMethodName        = "/ltrstchain.bridge.Msg/UpdateParams"
	Msg_RegisterBridgeAsset_FullMethodName = "/ltrstchain.bridge.Msg/RegisterBridgeAsset"
	Msg_UpdateBridgeAsset_FullMethodName   = "/ltrstchain.bridge.Msg/UpdateBridgeAsset"
	Msg_RemoveBridgeAsset_FullMethodName   = "/ltrstchain.bridge.Msg/RemoveBridgeAsset"
)

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams changes the module params. Authority-only.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// RegisterBridgeAsset adds a new asset entry. Authority-only by
	// default (Params.require_governance_registration).
	RegisterBridgeAsset(ctx context.Context, in *MsgRegisterBridgeAsset, opts ...grpc.CallOption) (*MsgRegisterBridgeAssetResponse, error)
	// UpdateBridgeAsset mutates display fields and/or verified flag.
	// Authority-only.
	UpdateBridgeAsset(ctx context.Context, in *MsgUpdateBridgeAsset, opts ...grpc.CallOption) (*MsgUpdateBridgeAssetResponse, error)
	// RemoveBridgeAsset deletes an entry. Does not claw back any bank
	// balances — x/bank tokens keep flowing. The entry removal only
	// affects what UIs decide to surface. Authority-only.
	RemoveBridgeAsset(ctx context.Context, in *MsgRemoveBridgeAsset, opts ...grpc.CallOption) (*MsgRemoveBridgeAssetResponse, error)
}

type msgClient struct {
	cc grpc.ClientConnInterface
}

func NewMsgClient(cc grpc.ClientConnInterface) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateParams_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RegisterBridgeAsset(ctx context.Context, in *MsgRegisterBridgeAsset, opts ...grpc.CallOption) (*MsgRegisterBridgeAssetResponse, error) {
	out := new(MsgRegisterBridgeAssetResponse)
	err := c.cc.Invoke(ctx, Msg_RegisterBridgeAsset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateBridgeAsset(ctx context.Context, in *MsgUpdateBridgeAsset, opts ...grpc.CallOption) (*MsgUpdateBridgeAssetResponse, error) {
	out := new(MsgUpdateBridgeAssetResponse)
	err := c.cc.Invoke(ctx, Msg_UpdateBridgeAsset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RemoveBridgeAsset(ctx context.Context, in *MsgRemoveBridgeAsset, opts ...grpc.CallOption) (*MsgRemoveBridgeAssetResponse, error) {
	out := new(MsgRemoveBridgeAssetResponse)
	err := c.cc.Invoke(ctx, Msg_RemoveBridgeAsset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
// All implementations must embed UnimplementedMsgServer
// for forward compatibility
type MsgServer interface {
	// UpdateParams changes the module params. Authority-only.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// RegisterBridgeAsset adds a new asset entry. Authority-only by
	// default (Params.require_governance_registration).
	RegisterBridgeAsset(context.Context, *MsgRegisterBridgeAsset) (*MsgRegisterBridgeAssetResponse, error)
	// UpdateBridgeAsset mutates display fields and/or verified flag.
	// Authority-only.
	UpdateBridgeAsset(context.Context, *MsgUpdateBridgeAsset) (*MsgUpdateBridgeAssetResponse, error)
	// RemoveBridgeAsset deletes an entry. Does not claw back any bank
	// balances — x/bank tokens keep flowing. The entry removal only
	// affects what UIs decide to surface. Authority-only.
	RemoveBridgeAsset(context.Context, *MsgRemoveBridgeAsset) (*MsgRemoveBridgeAssetResponse, error)
	mustEmbedUnimplementedMsgServer()
}

// UnimplementedMsgServer must be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (UnimplementedMsgServer) UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (UnimplementedMsgServer) RegisterBridgeAsset(context.Context, *MsgRegisterBridgeAsset) (*MsgRegisterBridgeAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterBridgeAsset not implemented")
}
func (UnimplementedMsgServer) UpdateBridgeAsset(context.Context, *MsgUpdateBridgeAsset) (*MsgUpdateBridgeAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBridgeAsset not implemented")
}
func (UnimplementedMsgServer) RemoveBridgeAsset(context.Context, *MsgRemoveBridgeAsset) (*MsgRemoveBridgeAssetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveBridgeAsset not implemented")
}
func (UnimplementedMsgServer) mustEmbedUnimplementedMsgServer() {}

// UnsafeMsgServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MsgServer will
// result in compilation errors.
type UnsafeMsgServer interface {
	mustEmbedUnimplementedMsgServer()
}

func RegisterMsgServer(s grpc.ServiceRegistrar, srv MsgServer) {
	s.RegisterService(&Msg_ServiceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateParams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RegisterBridgeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRegisterBridgeAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RegisterBridgeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RegisterBridgeAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RegisterBridgeAsset(ctx, req.(*MsgRegisterBridgeAsset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateBridgeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateBridgeAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateBridgeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_UpdateBridgeAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateBridgeAsset(ctx, req.(*MsgUpdateBridgeAsset))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RemoveBridgeAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRemoveBridgeAsset)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RemoveBridgeAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Msg_RemoveBridgeAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RemoveBridgeAsset(ctx, req.(*MsgRemoveBridgeAsset))
	}
	return interceptor(ctx, in, info, handler)
}

// Msg_ServiceDesc is the grpc.ServiceDesc for Msg service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Msg_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ltrstchain.bridge.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "RegisterBridgeAsset",
			Handler:    _Msg_RegisterBridgeAsset_Handler,
		},
		{
			MethodName: "UpdateBridgeAsset",
			Handler:    _Msg_UpdateBridgeAsset_Handler,
		},
		{
			MethodName: "RemoveBridgeAsset",
			Handler:    _Msg_RemoveBridgeAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ltrstchain/bridge/tx.proto",
}
